// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockworkflow

import (
	"context"
	"time"

	"github.com/alwitt/tasking/db"
	"github.com/alwitt/tasking/models"
	"github.com/alwitt/tasking/workflow"
	mock "github.com/stretchr/testify/mock"
)

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

type Client_Expecter struct {
	mock *mock.Mock
}

func (_m *Client) EXPECT() *Client_Expecter {
	return &Client_Expecter{mock: &_m.Mock}
}

// CancelWorkflow provides a mock function for the type Client
func (_mock *Client) CancelWorkflow(ctx context.Context, workflowID string, activeDBClient db.Database) error {
	ret := _mock.Called(ctx, workflowID, activeDBClient)

	if len(ret) == 0 {
		panic("no return value specified for CancelWorkflow")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, db.Database) error); ok {
		r0 = returnFunc(ctx, workflowID, activeDBClient)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Client_CancelWorkflow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelWorkflow'
type Client_CancelWorkflow_Call struct {
	*mock.Call
}

// CancelWorkflow is a helper method to define mock.On call
//   - ctx context.Context
//   - workflowID string
//   - activeDBClient db.Database
func (_e *Client_Expecter) CancelWorkflow(ctx interface{}, workflowID interface{}, activeDBClient interface{}) *Client_CancelWorkflow_Call {
	return &Client_CancelWorkflow_Call{Call: _e.mock.On("CancelWorkflow", ctx, workflowID, activeDBClient)}
}

func (_c *Client_CancelWorkflow_Call) Run(run func(ctx context.Context, workflowID string, activeDBClient db.Database)) *Client_CancelWorkflow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 db.Database
		if args[2] != nil {
			arg2 = args[2].(db.Database)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Client_CancelWorkflow_Call) Return(err error) *Client_CancelWorkflow_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Client_CancelWorkflow_Call) RunAndReturn(run func(ctx context.Context, workflowID string, activeDBClient db.Database) error) *Client_CancelWorkflow_Call {
	_c.Call.Return(run)
	return _c
}

// DefineAndRunWorkflow provides a mock function for the type Client
func (_mock *Client) DefineAndRunWorkflow(ctx context.Context, params workflow.DefineWorkflowParams, activeDBClient db.Database) (models.Workflow, error) {
	ret := _mock.Called(ctx, params, activeDBClient)

	if len(ret) == 0 {
		panic("no return value specified for DefineAndRunWorkflow")
	}

	var r0 models.Workflow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, workflow.DefineWorkflowParams, db.Database) (models.Workflow, error)); ok {
		return returnFunc(ctx, params, activeDBClient)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, workflow.DefineWorkflowParams, db.Database) models.Workflow); ok {
		r0 = returnFunc(ctx, params, activeDBClient)
	} else {
		r0 = ret.Get(0).(models.Workflow)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, workflow.DefineWorkflowParams, db.Database) error); ok {
		r1 = returnFunc(ctx, params, activeDBClient)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Client_DefineAndRunWorkflow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DefineAndRunWorkflow'
type Client_DefineAndRunWorkflow_Call struct {
	*mock.Call
}

// DefineAndRunWorkflow is a helper method to define mock.On call
//   - ctx context.Context
//   - params workflow.DefineWorkflowParams
//   - activeDBClient db.Database
func (_e *Client_Expecter) DefineAndRunWorkflow(ctx interface{}, params interface{}, activeDBClient interface{}) *Client_DefineAndRunWorkflow_Call {
	return &Client_DefineAndRunWorkflow_Call{Call: _e.mock.On("DefineAndRunWorkflow", ctx, params, activeDBClient)}
}

func (_c *Client_DefineAndRunWorkflow_Call) Run(run func(ctx context.Context, params workflow.DefineWorkflowParams, activeDBClient db.Database)) *Client_DefineAndRunWorkflow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 workflow.DefineWorkflowParams
		if args[1] != nil {
			arg1 = args[1].(workflow.DefineWorkflowParams)
		}
		var arg2 db.Database
		if args[2] != nil {
			arg2 = args[2].(db.Database)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Client_DefineAndRunWorkflow_Call) Return(workflow1 models.Workflow, err error) *Client_DefineAndRunWorkflow_Call {
	_c.Call.Return(workflow1, err)
	return _c
}

func (_c *Client_DefineAndRunWorkflow_Call) RunAndReturn(run func(ctx context.Context, params workflow.DefineWorkflowParams, activeDBClient db.Database) (models.Workflow, error)) *Client_DefineAndRunWorkflow_Call {
	_c.Call.Return(run)
	return _c
}

// DefineWorkflow provides a mock function for the type Client
func (_mock *Client) DefineWorkflow(ctx context.Context, params workflow.DefineWorkflowParams, activeDBClient db.Database) (models.Workflow, error) {
	ret := _mock.Called(ctx, params, activeDBClient)

	if len(ret) == 0 {
		panic("no return value specified for DefineWorkflow")
	}

	var r0 models.Workflow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, workflow.DefineWorkflowParams, db.Database) (models.Workflow, error)); ok {
		return returnFunc(ctx, params, activeDBClient)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, workflow.DefineWorkflowParams, db.Database) models.Workflow); ok {
		r0 = returnFunc(ctx, params, activeDBClient)
	} else {
		r0 = ret.Get(0).(models.Workflow)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, workflow.DefineWorkflowParams, db.Database) error); ok {
		r1 = returnFunc(ctx, params, activeDBClient)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Client_DefineWorkflow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DefineWorkflow'
type Client_DefineWorkflow_Call struct {
	*mock.Call
}

// DefineWorkflow is a helper method to define mock.On call
//   - ctx context.Context
//   - params workflow.DefineWorkflowParams
//   - activeDBClient db.Database
func (_e *Client_Expecter) DefineWorkflow(ctx interface{}, params interface{}, activeDBClient interface{}) *Client_DefineWorkflow_Call {
	return &Client_DefineWorkflow_Call{Call: _e.mock.On("DefineWorkflow", ctx, params, activeDBClient)}
}

func (_c *Client_DefineWorkflow_Call) Run(run func(ctx context.Context, params workflow.DefineWorkflowParams, activeDBClient db.Database)) *Client_DefineWorkflow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 workflow.DefineWorkflowParams
		if args[1] != nil {
			arg1 = args[1].(workflow.DefineWorkflowParams)
		}
		var arg2 db.Database
		if args[2] != nil {
			arg2 = args[2].(db.Database)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Client_DefineWorkflow_Call) Return(workflow1 models.Workflow, err error) *Client_DefineWorkflow_Call {
	_c.Call.Return(workflow1, err)
	return _c
}

func (_c *Client_DefineWorkflow_Call) RunAndReturn(run func(ctx context.Context, params workflow.DefineWorkflowParams, activeDBClient db.Database) (models.Workflow, error)) *Client_DefineWorkflow_Call {
	_c.Call.Return(run)
	return _c
}

// ReviveWorkflow provides a mock function for the type Client
func (_mock *Client) ReviveWorkflow(ctx context.Context, workflowID string, newDeadline *time.Time, activeDBClient db.Database) error {
	ret := _mock.Called(ctx, workflowID, newDeadline, activeDBClient)

	if len(ret) == 0 {
		panic("no return value specified for ReviveWorkflow")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *time.Time, db.Database) error); ok {
		r0 = returnFunc(ctx, workflowID, newDeadline, activeDBClient)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Client_ReviveWorkflow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReviveWorkflow'
type Client_ReviveWorkflow_Call struct {
	*mock.Call
}

// ReviveWorkflow is a helper method to define mock.On call
//   - ctx context.Context
//   - workflowID string
//   - newDeadline *time.Time
//   - activeDBClient db.Database
func (_e *Client_Expecter) ReviveWorkflow(ctx interface{}, workflowID interface{}, newDeadline interface{}, activeDBClient interface{}) *Client_ReviveWorkflow_Call {
	return &Client_ReviveWorkflow_Call{Call: _e.mock.On("ReviveWorkflow", ctx, workflowID, newDeadline, activeDBClient)}
}

func (_c *Client_ReviveWorkflow_Call) Run(run func(ctx context.Context, workflowID string, newDeadline *time.Time, activeDBClient db.Database)) *Client_ReviveWorkflow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *time.Time
		if args[2] != nil {
			arg2 = args[2].(*time.Time)
		}
		var arg3 db.Database
		if args[3] != nil {
			arg3 = args[3].(db.Database)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *Client_ReviveWorkflow_Call) Return(err error) *Client_ReviveWorkflow_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Client_ReviveWorkflow_Call) RunAndReturn(run func(ctx context.Context, workflowID string, newDeadline *time.Time, activeDBClient db.Database) error) *Client_ReviveWorkflow_Call {
	_c.Call.Return(run)
	return _c
}

// SubmitWorkflow provides a mock function for the type Client
func (_mock *Client) SubmitWorkflow(ctx context.Context, workflowID string) error {
	ret := _mock.Called(ctx, workflowID)

	if len(ret) == 0 {
		panic("no return value specified for SubmitWorkflow")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, workflowID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Client_SubmitWorkflow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SubmitWorkflow'
type Client_SubmitWorkflow_Call struct {
	*mock.Call
}

// SubmitWorkflow is a helper method to define mock.On call
//   - ctx context.Context
//   - workflowID string
func (_e *Client_Expecter) SubmitWorkflow(ctx interface{}, workflowID interface{}) *Client_SubmitWorkflow_Call {
	return &Client_SubmitWorkflow_Call{Call: _e.mock.On("SubmitWorkflow", ctx, workflowID)}
}

func (_c *Client_SubmitWorkflow_Call) Run(run func(ctx context.Context, workflowID string)) *Client_SubmitWorkflow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Client_SubmitWorkflow_Call) Return(err error) *Client_SubmitWorkflow_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Client_SubmitWorkflow_Call) RunAndReturn(run func(ctx context.Context, workflowID string) error) *Client_SubmitWorkflow_Call {
	_c.Call.Return(run)
	return _c
}
