// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocktask

import (
	"context"
	"time"

	"github.com/alwitt/tasking/db"
	"github.com/alwitt/tasking/models"
	mock "github.com/stretchr/testify/mock"
)

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

type Client_Expecter struct {
	mock *mock.Mock
}

func (_m *Client) EXPECT() *Client_Expecter {
	return &Client_Expecter{mock: &_m.Mock}
}

// CancelTask provides a mock function for the type Client
func (_mock *Client) CancelTask(ctx context.Context, taskID string, activeDBClient db.Database) error {
	ret := _mock.Called(ctx, taskID, activeDBClient)

	if len(ret) == 0 {
		panic("no return value specified for CancelTask")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, db.Database) error); ok {
		r0 = returnFunc(ctx, taskID, activeDBClient)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Client_CancelTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelTask'
type Client_CancelTask_Call struct {
	*mock.Call
}

// CancelTask is a helper method to define mock.On call
//   - ctx context.Context
//   - taskID string
//   - activeDBClient db.Database
func (_e *Client_Expecter) CancelTask(ctx interface{}, taskID interface{}, activeDBClient interface{}) *Client_CancelTask_Call {
	return &Client_CancelTask_Call{Call: _e.mock.On("CancelTask", ctx, taskID, activeDBClient)}
}

func (_c *Client_CancelTask_Call) Run(run func(ctx context.Context, taskID string, activeDBClient db.Database)) *Client_CancelTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 db.Database
		if args[2] != nil {
			arg2 = args[2].(db.Database)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Client_CancelTask_Call) Return(err error) *Client_CancelTask_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Client_CancelTask_Call) RunAndReturn(run func(ctx context.Context, taskID string, activeDBClient db.Database) error) *Client_CancelTask_Call {
	_c.Call.Return(run)
	return _c
}

// DefineAndRunImmediateOneShotTask provides a mock function for the type Client
func (_mock *Client) DefineAndRunImmediateOneShotTask(ctx context.Context, name string, parameters any, metadata any, deadline *time.Time, activeDBClient db.Database) (models.Task, error) {
	ret := _mock.Called(ctx, name, parameters, metadata, deadline, activeDBClient)

	if len(ret) == 0 {
		panic("no return value specified for DefineAndRunImmediateOneShotTask")
	}

	var r0 models.Task
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, any, any, *time.Time, db.Database) (models.Task, error)); ok {
		return returnFunc(ctx, name, parameters, metadata, deadline, activeDBClient)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, any, any, *time.Time, db.Database) models.Task); ok {
		r0 = returnFunc(ctx, name, parameters, metadata, deadline, activeDBClient)
	} else {
		r0 = ret.Get(0).(models.Task)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, any, any, *time.Time, db.Database) error); ok {
		r1 = returnFunc(ctx, name, parameters, metadata, deadline, activeDBClient)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Client_DefineAndRunImmediateOneShotTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DefineAndRunImmediateOneShotTask'
type Client_DefineAndRunImmediateOneShotTask_Call struct {
	*mock.Call
}

// DefineAndRunImmediateOneShotTask is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - parameters any
//   - metadata any
//   - deadline *time.Time
//   - activeDBClient db.Database
func (_e *Client_Expecter) DefineAndRunImmediateOneShotTask(ctx interface{}, name interface{}, parameters interface{}, metadata interface{}, deadline interface{}, activeDBClient interface{}) *Client_DefineAndRunImmediateOneShotTask_Call {
	return &Client_DefineAndRunImmediateOneShotTask_Call{Call: _e.mock.On("DefineAndRunImmediateOneShotTask", ctx, name, parameters, metadata, deadline, activeDBClient)}
}

func (_c *Client_DefineAndRunImmediateOneShotTask_Call) Run(run func(ctx context.Context, name string, parameters any, metadata any, deadline *time.Time, activeDBClient db.Database)) *Client_DefineAndRunImmediateOneShotTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 any
		if args[2] != nil {
			arg2 = args[2].(any)
		}
		var arg3 any
		if args[3] != nil {
			arg3 = args[3].(any)
		}
		var arg4 *time.Time
		if args[4] != nil {
			arg4 = args[4].(*time.Time)
		}
		var arg5 db.Database
		if args[5] != nil {
			arg5 = args[5].(db.Database)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *Client_DefineAndRunImmediateOneShotTask_Call) Return(task models.Task, err error) *Client_DefineAndRunImmediateOneShotTask_Call {
	_c.Call.Return(task, err)
	return _c
}

func (_c *Client_DefineAndRunImmediateOneShotTask_Call) RunAndReturn(run func(ctx context.Context, name string, parameters any, metadata any, deadline *time.Time, activeDBClient db.Database) (models.Task, error)) *Client_DefineAndRunImmediateOneShotTask_Call {
	_c.Call.Return(run)
	return _c
}

// DefineAndRunScheduledOneShotTask provides a mock function for the type Client
func (_mock *Client) DefineAndRunScheduledOneShotTask(ctx context.Context, name string, parameters any, metadata any, targetRuntime time.Time, deadline *time.Time, activeDBClient db.Database) (models.Task, error) {
	ret := _mock.Called(ctx, name, parameters, metadata, targetRuntime, deadline, activeDBClient)

	if len(ret) == 0 {
		panic("no return value specified for DefineAndRunScheduledOneShotTask")
	}

	var r0 models.Task
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, any, any, time.Time, *time.Time, db.Database) (models.Task, error)); ok {
		return returnFunc(ctx, name, parameters, metadata, targetRuntime, deadline, activeDBClient)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, any, any, time.Time, *time.Time, db.Database) models.Task); ok {
		r0 = returnFunc(ctx, name, parameters, metadata, targetRuntime, deadline, activeDBClient)
	} else {
		r0 = ret.Get(0).(models.Task)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, any, any, time.Time, *time.Time, db.Database) error); ok {
		r1 = returnFunc(ctx, name, parameters, metadata, targetRuntime, deadline, activeDBClient)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Client_DefineAndRunScheduledOneShotTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DefineAndRunScheduledOneShotTask'
type Client_DefineAndRunScheduledOneShotTask_Call struct {
	*mock.Call
}

// DefineAndRunScheduledOneShotTask is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - parameters any
//   - metadata any
//   - targetRuntime time.Time
//   - deadline *time.Time
//   - activeDBClient db.Database
func (_e *Client_Expecter) DefineAndRunScheduledOneShotTask(ctx interface{}, name interface{}, parameters interface{}, metadata interface{}, targetRuntime interface{}, deadline interface{}, activeDBClient interface{}) *Client_DefineAndRunScheduledOneShotTask_Call {
	return &Client_DefineAndRunScheduledOneShotTask_Call{Call: _e.mock.On("DefineAndRunScheduledOneShotTask", ctx, name, parameters, metadata, targetRuntime, deadline, activeDBClient)}
}

func (_c *Client_DefineAndRunScheduledOneShotTask_Call) Run(run func(ctx context.Context, name string, parameters any, metadata any, targetRuntime time.Time, deadline *time.Time, activeDBClient db.Database)) *Client_DefineAndRunScheduledOneShotTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 any
		if args[2] != nil {
			arg2 = args[2].(any)
		}
		var arg3 any
		if args[3] != nil {
			arg3 = args[3].(any)
		}
		var arg4 time.Time
		if args[4] != nil {
			arg4 = args[4].(time.Time)
		}
		var arg5 *time.Time
		if args[5] != nil {
			arg5 = args[5].(*time.Time)
		}
		var arg6 db.Database
		if args[6] != nil {
			arg6 = args[6].(db.Database)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6,
		)
	})
	return _c
}

func (_c *Client_DefineAndRunScheduledOneShotTask_Call) Return(task models.Task, err error) *Client_DefineAndRunScheduledOneShotTask_Call {
	_c.Call.Return(task, err)
	return _c
}

func (_c *Client_DefineAndRunScheduledOneShotTask_Call) RunAndReturn(run func(ctx context.Context, name string, parameters any, metadata any, targetRuntime time.Time, deadline *time.Time, activeDBClient db.Database) (models.Task, error)) *Client_DefineAndRunScheduledOneShotTask_Call {
	_c.Call.Return(run)
	return _c
}
