// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocktask

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewExecutor creates a new instance of Executor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewExecutor(t interface {
	mock.TestingT
	Cleanup(func())
}) *Executor {
	mock := &Executor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Executor is an autogenerated mock type for the Executor type
type Executor struct {
	mock.Mock
}

type Executor_Expecter struct {
	mock *mock.Mock
}

func (_m *Executor) EXPECT() *Executor_Expecter {
	return &Executor_Expecter{mock: &_m.Mock}
}

// ProcessExecutionInstance provides a mock function for the type Executor
func (_mock *Executor) ProcessExecutionInstance(ctx context.Context, instanceID string) error {
	ret := _mock.Called(ctx, instanceID)

	if len(ret) == 0 {
		panic("no return value specified for ProcessExecutionInstance")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, instanceID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Executor_ProcessExecutionInstance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProcessExecutionInstance'
type Executor_ProcessExecutionInstance_Call struct {
	*mock.Call
}

// ProcessExecutionInstance is a helper method to define mock.On call
//   - ctx context.Context
//   - instanceID string
func (_e *Executor_Expecter) ProcessExecutionInstance(ctx interface{}, instanceID interface{}) *Executor_ProcessExecutionInstance_Call {
	return &Executor_ProcessExecutionInstance_Call{Call: _e.mock.On("ProcessExecutionInstance", ctx, instanceID)}
}

func (_c *Executor_ProcessExecutionInstance_Call) Run(run func(ctx context.Context, instanceID string)) *Executor_ProcessExecutionInstance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Executor_ProcessExecutionInstance_Call) Return(err error) *Executor_ProcessExecutionInstance_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Executor_ProcessExecutionInstance_Call) RunAndReturn(run func(ctx context.Context, instanceID string) error) *Executor_ProcessExecutionInstance_Call {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function for the type Executor
func (_mock *Executor) Stop(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Stop")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Executor_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type Executor_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Executor_Expecter) Stop(ctx interface{}) *Executor_Stop_Call {
	return &Executor_Stop_Call{Call: _e.mock.On("Stop", ctx)}
}

func (_c *Executor_Stop_Call) Run(run func(ctx context.Context)) *Executor_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Executor_Stop_Call) Return(err error) *Executor_Stop_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Executor_Stop_Call) RunAndReturn(run func(ctx context.Context) error) *Executor_Stop_Call {
	_c.Call.Return(run)
	return _c
}
