// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocktask

import (
	"context"

	"github.com/alwitt/tasking/db"
	mock "github.com/stretchr/testify/mock"
)

// NewReceiver creates a new instance of Receiver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReceiver(t interface {
	mock.TestingT
	Cleanup(func())
}) *Receiver {
	mock := &Receiver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Receiver is an autogenerated mock type for the Receiver type
type Receiver struct {
	mock.Mock
}

type Receiver_Expecter struct {
	mock *mock.Mock
}

func (_m *Receiver) EXPECT() *Receiver_Expecter {
	return &Receiver_Expecter{mock: &_m.Mock}
}

// Initialize provides a mock function for the type Receiver
func (_mock *Receiver) Initialize(ctx context.Context, activeDBClient db.Database) error {
	ret := _mock.Called(ctx, activeDBClient)

	if len(ret) == 0 {
		panic("no return value specified for Initialize")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.Database) error); ok {
		r0 = returnFunc(ctx, activeDBClient)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Receiver_Initialize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Initialize'
type Receiver_Initialize_Call struct {
	*mock.Call
}

// Initialize is a helper method to define mock.On call
//   - ctx context.Context
//   - activeDBClient db.Database
func (_e *Receiver_Expecter) Initialize(ctx interface{}, activeDBClient interface{}) *Receiver_Initialize_Call {
	return &Receiver_Initialize_Call{Call: _e.mock.On("Initialize", ctx, activeDBClient)}
}

func (_c *Receiver_Initialize_Call) Run(run func(ctx context.Context, activeDBClient db.Database)) *Receiver_Initialize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 db.Database
		if args[1] != nil {
			arg1 = args[1].(db.Database)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Receiver_Initialize_Call) Return(err error) *Receiver_Initialize_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Receiver_Initialize_Call) RunAndReturn(run func(ctx context.Context, activeDBClient db.Database) error) *Receiver_Initialize_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function for the type Receiver
func (_mock *Receiver) Start(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Receiver_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type Receiver_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Receiver_Expecter) Start(ctx interface{}) *Receiver_Start_Call {
	return &Receiver_Start_Call{Call: _e.mock.On("Start", ctx)}
}

func (_c *Receiver_Start_Call) Run(run func(ctx context.Context)) *Receiver_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Receiver_Start_Call) Return(err error) *Receiver_Start_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Receiver_Start_Call) RunAndReturn(run func(ctx context.Context) error) *Receiver_Start_Call {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function for the type Receiver
func (_mock *Receiver) Stop(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Stop")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Receiver_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type Receiver_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Receiver_Expecter) Stop(ctx interface{}) *Receiver_Stop_Call {
	return &Receiver_Stop_Call{Call: _e.mock.On("Stop", ctx)}
}

func (_c *Receiver_Stop_Call) Run(run func(ctx context.Context)) *Receiver_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Receiver_Stop_Call) Return(err error) *Receiver_Stop_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Receiver_Stop_Call) RunAndReturn(run func(ctx context.Context) error) *Receiver_Stop_Call {
	_c.Call.Return(run)
	return _c
}
