// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockmodels

import (
	"context"

	"github.com/alwitt/tasking/models"
	mock "github.com/stretchr/testify/mock"
)

// NewTaskExecutionProcessor creates a new instance of TaskExecutionProcessor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTaskExecutionProcessor(t interface {
	mock.TestingT
	Cleanup(func())
}) *TaskExecutionProcessor {
	mock := &TaskExecutionProcessor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TaskExecutionProcessor is an autogenerated mock type for the TaskExecutionProcessor type
type TaskExecutionProcessor struct {
	mock.Mock
}

type TaskExecutionProcessor_Expecter struct {
	mock *mock.Mock
}

func (_m *TaskExecutionProcessor) EXPECT() *TaskExecutionProcessor_Expecter {
	return &TaskExecutionProcessor_Expecter{mock: &_m.Mock}
}

// ProcessTaskExecution provides a mock function for the type TaskExecutionProcessor
func (_mock *TaskExecutionProcessor) ProcessTaskExecution(ctx context.Context, taskEntry models.Task, executeEntry models.TaskExecution) error {
	ret := _mock.Called(ctx, taskEntry, executeEntry)

	if len(ret) == 0 {
		panic("no return value specified for ProcessTaskExecution")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Task, models.TaskExecution) error); ok {
		r0 = returnFunc(ctx, taskEntry, executeEntry)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// TaskExecutionProcessor_ProcessTaskExecution_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProcessTaskExecution'
type TaskExecutionProcessor_ProcessTaskExecution_Call struct {
	*mock.Call
}

// ProcessTaskExecution is a helper method to define mock.On call
//   - ctx context.Context
//   - taskEntry models.Task
//   - executeEntry models.TaskExecution
func (_e *TaskExecutionProcessor_Expecter) ProcessTaskExecution(ctx interface{}, taskEntry interface{}, executeEntry interface{}) *TaskExecutionProcessor_ProcessTaskExecution_Call {
	return &TaskExecutionProcessor_ProcessTaskExecution_Call{Call: _e.mock.On("ProcessTaskExecution", ctx, taskEntry, executeEntry)}
}

func (_c *TaskExecutionProcessor_ProcessTaskExecution_Call) Run(run func(ctx context.Context, taskEntry models.Task, executeEntry models.TaskExecution)) *TaskExecutionProcessor_ProcessTaskExecution_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.Task
		if args[1] != nil {
			arg1 = args[1].(models.Task)
		}
		var arg2 models.TaskExecution
		if args[2] != nil {
			arg2 = args[2].(models.TaskExecution)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *TaskExecutionProcessor_ProcessTaskExecution_Call) Return(err error) *TaskExecutionProcessor_ProcessTaskExecution_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *TaskExecutionProcessor_ProcessTaskExecution_Call) RunAndReturn(run func(ctx context.Context, taskEntry models.Task, executeEntry models.TaskExecution) error) *TaskExecutionProcessor_ProcessTaskExecution_Call {
	_c.Call.Return(run)
	return _c
}
