// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockmodels

import (
	"context"

	"github.com/alwitt/tasking/models"
	mock "github.com/stretchr/testify/mock"
)

// NewWorkflowStepProcessor creates a new instance of WorkflowStepProcessor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWorkflowStepProcessor(t interface {
	mock.TestingT
	Cleanup(func())
}) *WorkflowStepProcessor {
	mock := &WorkflowStepProcessor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// WorkflowStepProcessor is an autogenerated mock type for the WorkflowStepProcessor type
type WorkflowStepProcessor struct {
	mock.Mock
}

type WorkflowStepProcessor_Expecter struct {
	mock *mock.Mock
}

func (_m *WorkflowStepProcessor) EXPECT() *WorkflowStepProcessor_Expecter {
	return &WorkflowStepProcessor_Expecter{mock: &_m.Mock}
}

// ProcessWorkflowStep provides a mock function for the type WorkflowStepProcessor
func (_mock *WorkflowStepProcessor) ProcessWorkflowStep(ctx context.Context, workflowEntry models.Workflow, stepEntry models.WorkflowStep) error {
	ret := _mock.Called(ctx, workflowEntry, stepEntry)

	if len(ret) == 0 {
		panic("no return value specified for ProcessWorkflowStep")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Workflow, models.WorkflowStep) error); ok {
		r0 = returnFunc(ctx, workflowEntry, stepEntry)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// WorkflowStepProcessor_ProcessWorkflowStep_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProcessWorkflowStep'
type WorkflowStepProcessor_ProcessWorkflowStep_Call struct {
	*mock.Call
}

// ProcessWorkflowStep is a helper method to define mock.On call
//   - ctx context.Context
//   - workflowEntry models.Workflow
//   - stepEntry models.WorkflowStep
func (_e *WorkflowStepProcessor_Expecter) ProcessWorkflowStep(ctx interface{}, workflowEntry interface{}, stepEntry interface{}) *WorkflowStepProcessor_ProcessWorkflowStep_Call {
	return &WorkflowStepProcessor_ProcessWorkflowStep_Call{Call: _e.mock.On("ProcessWorkflowStep", ctx, workflowEntry, stepEntry)}
}

func (_c *WorkflowStepProcessor_ProcessWorkflowStep_Call) Run(run func(ctx context.Context, workflowEntry models.Workflow, stepEntry models.WorkflowStep)) *WorkflowStepProcessor_ProcessWorkflowStep_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.Workflow
		if args[1] != nil {
			arg1 = args[1].(models.Workflow)
		}
		var arg2 models.WorkflowStep
		if args[2] != nil {
			arg2 = args[2].(models.WorkflowStep)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *WorkflowStepProcessor_ProcessWorkflowStep_Call) Return(err error) *WorkflowStepProcessor_ProcessWorkflowStep_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *WorkflowStepProcessor_ProcessWorkflowStep_Call) RunAndReturn(run func(ctx context.Context, workflowEntry models.Workflow, stepEntry models.WorkflowStep) error) *WorkflowStepProcessor_ProcessWorkflowStep_Call {
	_c.Call.Return(run)
	return _c
}
