// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockdb

import (
	"context"

	"github.com/alwitt/tasking/db"
	mock "github.com/stretchr/testify/mock"
	"gorm.io/gorm"
)

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

type Client_Expecter struct {
	mock *mock.Mock
}

func (_m *Client) EXPECT() *Client_Expecter {
	return &Client_Expecter{mock: &_m.Mock}
}

// RunSQLInTransaction provides a mock function for the type Client
func (_mock *Client) RunSQLInTransaction(ctx context.Context, coreLogic func(ctx context.Context, tx *gorm.DB) error) error {
	ret := _mock.Called(ctx, coreLogic)

	if len(ret) == 0 {
		panic("no return value specified for RunSQLInTransaction")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, func(ctx context.Context, tx *gorm.DB) error) error); ok {
		r0 = returnFunc(ctx, coreLogic)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Client_RunSQLInTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunSQLInTransaction'
type Client_RunSQLInTransaction_Call struct {
	*mock.Call
}

// RunSQLInTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - coreLogic func(ctx context.Context, tx *gorm.DB) error
func (_e *Client_Expecter) RunSQLInTransaction(ctx interface{}, coreLogic interface{}) *Client_RunSQLInTransaction_Call {
	return &Client_RunSQLInTransaction_Call{Call: _e.mock.On("RunSQLInTransaction", ctx, coreLogic)}
}

func (_c *Client_RunSQLInTransaction_Call) Run(run func(ctx context.Context, coreLogic func(ctx context.Context, tx *gorm.DB) error)) *Client_RunSQLInTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 func(ctx context.Context, tx *gorm.DB) error
		if args[1] != nil {
			arg1 = args[1].(func(ctx context.Context, tx *gorm.DB) error)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Client_RunSQLInTransaction_Call) Return(err error) *Client_RunSQLInTransaction_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Client_RunSQLInTransaction_Call) RunAndReturn(run func(ctx context.Context, coreLogic func(ctx context.Context, tx *gorm.DB) error) error) *Client_RunSQLInTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// UseDatabaseInTransaction provides a mock function for the type Client
func (_mock *Client) UseDatabaseInTransaction(ctx context.Context, coreLogic func(ctx context.Context, dbClient db.Database) error) error {
	ret := _mock.Called(ctx, coreLogic)

	if len(ret) == 0 {
		panic("no return value specified for UseDatabaseInTransaction")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, func(ctx context.Context, dbClient db.Database) error) error); ok {
		r0 = returnFunc(ctx, coreLogic)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Client_UseDatabaseInTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UseDatabaseInTransaction'
type Client_UseDatabaseInTransaction_Call struct {
	*mock.Call
}

// UseDatabaseInTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - coreLogic func(ctx context.Context, dbClient db.Database) error
func (_e *Client_Expecter) UseDatabaseInTransaction(ctx interface{}, coreLogic interface{}) *Client_UseDatabaseInTransaction_Call {
	return &Client_UseDatabaseInTransaction_Call{Call: _e.mock.On("UseDatabaseInTransaction", ctx, coreLogic)}
}

func (_c *Client_UseDatabaseInTransaction_Call) Run(run func(ctx context.Context, coreLogic func(ctx context.Context, dbClient db.Database) error)) *Client_UseDatabaseInTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 func(ctx context.Context, dbClient db.Database) error
		if args[1] != nil {
			arg1 = args[1].(func(ctx context.Context, dbClient db.Database) error)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Client_UseDatabaseInTransaction_Call) Return(err error) *Client_UseDatabaseInTransaction_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Client_UseDatabaseInTransaction_Call) RunAndReturn(run func(ctx context.Context, coreLogic func(ctx context.Context, dbClient db.Database) error) error) *Client_UseDatabaseInTransaction_Call {
	_c.Call.Return(run)
	return _c
}
