// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockdb

import (
	"context"
	"time"

	"github.com/alwitt/tasking/db"
	"github.com/alwitt/tasking/models"
	mock "github.com/stretchr/testify/mock"
)

// NewDatabase creates a new instance of Database. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDatabase(t interface {
	mock.TestingT
	Cleanup(func())
}) *Database {
	mock := &Database{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Database is an autogenerated mock type for the Database type
type Database struct {
	mock.Mock
}

type Database_Expecter struct {
	mock *mock.Mock
}

func (_m *Database) EXPECT() *Database_Expecter {
	return &Database_Expecter{mock: &_m.Mock}
}

// DefineNewOneShotTask provides a mock function for the type Database
func (_mock *Database) DefineNewOneShotTask(ctx context.Context, params db.NewTaskParameter) (models.Task, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for DefineNewOneShotTask")
	}

	var r0 models.Task
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.NewTaskParameter) (models.Task, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.NewTaskParameter) models.Task); ok {
		r0 = returnFunc(ctx, params)
	} else {
		r0 = ret.Get(0).(models.Task)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, db.NewTaskParameter) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Database_DefineNewOneShotTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DefineNewOneShotTask'
type Database_DefineNewOneShotTask_Call struct {
	*mock.Call
}

// DefineNewOneShotTask is a helper method to define mock.On call
//   - ctx context.Context
//   - params db.NewTaskParameter
func (_e *Database_Expecter) DefineNewOneShotTask(ctx interface{}, params interface{}) *Database_DefineNewOneShotTask_Call {
	return &Database_DefineNewOneShotTask_Call{Call: _e.mock.On("DefineNewOneShotTask", ctx, params)}
}

func (_c *Database_DefineNewOneShotTask_Call) Run(run func(ctx context.Context, params db.NewTaskParameter)) *Database_DefineNewOneShotTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 db.NewTaskParameter
		if args[1] != nil {
			arg1 = args[1].(db.NewTaskParameter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Database_DefineNewOneShotTask_Call) Return(task models.Task, err error) *Database_DefineNewOneShotTask_Call {
	_c.Call.Return(task, err)
	return _c
}

func (_c *Database_DefineNewOneShotTask_Call) RunAndReturn(run func(ctx context.Context, params db.NewTaskParameter) (models.Task, error)) *Database_DefineNewOneShotTask_Call {
	_c.Call.Return(run)
	return _c
}

// DefineNewScheduledOneShotTask provides a mock function for the type Database
func (_mock *Database) DefineNewScheduledOneShotTask(ctx context.Context, params db.NewTaskParameter, targetRuntime time.Time) (models.Task, error) {
	ret := _mock.Called(ctx, params, targetRuntime)

	if len(ret) == 0 {
		panic("no return value specified for DefineNewScheduledOneShotTask")
	}

	var r0 models.Task
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.NewTaskParameter, time.Time) (models.Task, error)); ok {
		return returnFunc(ctx, params, targetRuntime)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.NewTaskParameter, time.Time) models.Task); ok {
		r0 = returnFunc(ctx, params, targetRuntime)
	} else {
		r0 = ret.Get(0).(models.Task)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, db.NewTaskParameter, time.Time) error); ok {
		r1 = returnFunc(ctx, params, targetRuntime)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Database_DefineNewScheduledOneShotTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DefineNewScheduledOneShotTask'
type Database_DefineNewScheduledOneShotTask_Call struct {
	*mock.Call
}

// DefineNewScheduledOneShotTask is a helper method to define mock.On call
//   - ctx context.Context
//   - params db.NewTaskParameter
//   - targetRuntime time.Time
func (_e *Database_Expecter) DefineNewScheduledOneShotTask(ctx interface{}, params interface{}, targetRuntime interface{}) *Database_DefineNewScheduledOneShotTask_Call {
	return &Database_DefineNewScheduledOneShotTask_Call{Call: _e.mock.On("DefineNewScheduledOneShotTask", ctx, params, targetRuntime)}
}

func (_c *Database_DefineNewScheduledOneShotTask_Call) Run(run func(ctx context.Context, params db.NewTaskParameter, targetRuntime time.Time)) *Database_DefineNewScheduledOneShotTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 db.NewTaskParameter
		if args[1] != nil {
			arg1 = args[1].(db.NewTaskParameter)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Database_DefineNewScheduledOneShotTask_Call) Return(task models.Task, err error) *Database_DefineNewScheduledOneShotTask_Call {
	_c.Call.Return(task, err)
	return _c
}

func (_c *Database_DefineNewScheduledOneShotTask_Call) RunAndReturn(run func(ctx context.Context, params db.NewTaskParameter, targetRuntime time.Time) (models.Task, error)) *Database_DefineNewScheduledOneShotTask_Call {
	_c.Call.Return(run)
	return _c
}

// DefineNewTaskExecInstance provides a mock function for the type Database
func (_mock *Database) DefineNewTaskExecInstance(ctx context.Context, task models.Task) (models.TaskExecution, error) {
	ret := _mock.Called(ctx, task)

	if len(ret) == 0 {
		panic("no return value specified for DefineNewTaskExecInstance")
	}

	var r0 models.TaskExecution
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Task) (models.TaskExecution, error)); ok {
		return returnFunc(ctx, task)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Task) models.TaskExecution); ok {
		r0 = returnFunc(ctx, task)
	} else {
		r0 = ret.Get(0).(models.TaskExecution)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.Task) error); ok {
		r1 = returnFunc(ctx, task)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Database_DefineNewTaskExecInstance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DefineNewTaskExecInstance'
type Database_DefineNewTaskExecInstance_Call struct {
	*mock.Call
}

// DefineNewTaskExecInstance is a helper method to define mock.On call
//   - ctx context.Context
//   - task models.Task
func (_e *Database_Expecter) DefineNewTaskExecInstance(ctx interface{}, task interface{}) *Database_DefineNewTaskExecInstance_Call {
	return &Database_DefineNewTaskExecInstance_Call{Call: _e.mock.On("DefineNewTaskExecInstance", ctx, task)}
}

func (_c *Database_DefineNewTaskExecInstance_Call) Run(run func(ctx context.Context, task models.Task)) *Database_DefineNewTaskExecInstance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.Task
		if args[1] != nil {
			arg1 = args[1].(models.Task)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Database_DefineNewTaskExecInstance_Call) Return(taskExecution models.TaskExecution, err error) *Database_DefineNewTaskExecInstance_Call {
	_c.Call.Return(taskExecution, err)
	return _c
}

func (_c *Database_DefineNewTaskExecInstance_Call) RunAndReturn(run func(ctx context.Context, task models.Task) (models.TaskExecution, error)) *Database_DefineNewTaskExecInstance_Call {
	_c.Call.Return(run)
	return _c
}

// DefineNewTaskRetryExecInstance provides a mock function for the type Database
func (_mock *Database) DefineNewTaskRetryExecInstance(ctx context.Context, task models.Task, failedEntry models.TaskExecution, targetRunTime time.Time) (models.TaskExecution, error) {
	ret := _mock.Called(ctx, task, failedEntry, targetRunTime)

	if len(ret) == 0 {
		panic("no return value specified for DefineNewTaskRetryExecInstance")
	}

	var r0 models.TaskExecution
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Task, models.TaskExecution, time.Time) (models.TaskExecution, error)); ok {
		return returnFunc(ctx, task, failedEntry, targetRunTime)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Task, models.TaskExecution, time.Time) models.TaskExecution); ok {
		r0 = returnFunc(ctx, task, failedEntry, targetRunTime)
	} else {
		r0 = ret.Get(0).(models.TaskExecution)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.Task, models.TaskExecution, time.Time) error); ok {
		r1 = returnFunc(ctx, task, failedEntry, targetRunTime)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Database_DefineNewTaskRetryExecInstance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DefineNewTaskRetryExecInstance'
type Database_DefineNewTaskRetryExecInstance_Call struct {
	*mock.Call
}

// DefineNewTaskRetryExecInstance is a helper method to define mock.On call
//   - ctx context.Context
//   - task models.Task
//   - failedEntry models.TaskExecution
//   - targetRunTime time.Time
func (_e *Database_Expecter) DefineNewTaskRetryExecInstance(ctx interface{}, task interface{}, failedEntry interface{}, targetRunTime interface{}) *Database_DefineNewTaskRetryExecInstance_Call {
	return &Database_DefineNewTaskRetryExecInstance_Call{Call: _e.mock.On("DefineNewTaskRetryExecInstance", ctx, task, failedEntry, targetRunTime)}
}

func (_c *Database_DefineNewTaskRetryExecInstance_Call) Run(run func(ctx context.Context, task models.Task, failedEntry models.TaskExecution, targetRunTime time.Time)) *Database_DefineNewTaskRetryExecInstance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.Task
		if args[1] != nil {
			arg1 = args[1].(models.Task)
		}
		var arg2 models.TaskExecution
		if args[2] != nil {
			arg2 = args[2].(models.TaskExecution)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *Database_DefineNewTaskRetryExecInstance_Call) Return(taskExecution models.TaskExecution, err error) *Database_DefineNewTaskRetryExecInstance_Call {
	_c.Call.Return(taskExecution, err)
	return _c
}

func (_c *Database_DefineNewTaskRetryExecInstance_Call) RunAndReturn(run func(ctx context.Context, task models.Task, failedEntry models.TaskExecution, targetRunTime time.Time) (models.TaskExecution, error)) *Database_DefineNewTaskRetryExecInstance_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTask provides a mock function for the type Database
func (_mock *Database) DeleteTask(ctx context.Context, taskID string) error {
	ret := _mock.Called(ctx, taskID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTask")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, taskID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Database_DeleteTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTask'
type Database_DeleteTask_Call struct {
	*mock.Call
}

// DeleteTask is a helper method to define mock.On call
//   - ctx context.Context
//   - taskID string
func (_e *Database_Expecter) DeleteTask(ctx interface{}, taskID interface{}) *Database_DeleteTask_Call {
	return &Database_DeleteTask_Call{Call: _e.mock.On("DeleteTask", ctx, taskID)}
}

func (_c *Database_DeleteTask_Call) Run(run func(ctx context.Context, taskID string)) *Database_DeleteTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Database_DeleteTask_Call) Return(err error) *Database_DeleteTask_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Database_DeleteTask_Call) RunAndReturn(run func(ctx context.Context, taskID string) error) *Database_DeleteTask_Call {
	_c.Call.Return(run)
	return _c
}

// GetTask provides a mock function for the type Database
func (_mock *Database) GetTask(ctx context.Context, taskID string) (models.Task, error) {
	ret := _mock.Called(ctx, taskID)

	if len(ret) == 0 {
		panic("no return value specified for GetTask")
	}

	var r0 models.Task
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (models.Task, error)); ok {
		return returnFunc(ctx, taskID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) models.Task); ok {
		r0 = returnFunc(ctx, taskID)
	} else {
		r0 = ret.Get(0).(models.Task)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, taskID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Database_GetTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTask'
type Database_GetTask_Call struct {
	*mock.Call
}

// GetTask is a helper method to define mock.On call
//   - ctx context.Context
//   - taskID string
func (_e *Database_Expecter) GetTask(ctx interface{}, taskID interface{}) *Database_GetTask_Call {
	return &Database_GetTask_Call{Call: _e.mock.On("GetTask", ctx, taskID)}
}

func (_c *Database_GetTask_Call) Run(run func(ctx context.Context, taskID string)) *Database_GetTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Database_GetTask_Call) Return(task models.Task, err error) *Database_GetTask_Call {
	_c.Call.Return(task, err)
	return _c
}

func (_c *Database_GetTask_Call) RunAndReturn(run func(ctx context.Context, taskID string) (models.Task, error)) *Database_GetTask_Call {
	_c.Call.Return(run)
	return _c
}

// GetTaskExecution provides a mock function for the type Database
func (_mock *Database) GetTaskExecution(ctx context.Context, instanceID string) (models.TaskExecution, error) {
	ret := _mock.Called(ctx, instanceID)

	if len(ret) == 0 {
		panic("no return value specified for GetTaskExecution")
	}

	var r0 models.TaskExecution
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (models.TaskExecution, error)); ok {
		return returnFunc(ctx, instanceID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) models.TaskExecution); ok {
		r0 = returnFunc(ctx, instanceID)
	} else {
		r0 = ret.Get(0).(models.TaskExecution)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, instanceID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Database_GetTaskExecution_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTaskExecution'
type Database_GetTaskExecution_Call struct {
	*mock.Call
}

// GetTaskExecution is a helper method to define mock.On call
//   - ctx context.Context
//   - instanceID string
func (_e *Database_Expecter) GetTaskExecution(ctx interface{}, instanceID interface{}) *Database_GetTaskExecution_Call {
	return &Database_GetTaskExecution_Call{Call: _e.mock.On("GetTaskExecution", ctx, instanceID)}
}

func (_c *Database_GetTaskExecution_Call) Run(run func(ctx context.Context, instanceID string)) *Database_GetTaskExecution_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Database_GetTaskExecution_Call) Return(taskExecution models.TaskExecution, err error) *Database_GetTaskExecution_Call {
	_c.Call.Return(taskExecution, err)
	return _c
}

func (_c *Database_GetTaskExecution_Call) RunAndReturn(run func(ctx context.Context, instanceID string) (models.TaskExecution, error)) *Database_GetTaskExecution_Call {
	_c.Call.Return(run)
	return _c
}

// ListAllExecutions provides a mock function for the type Database
func (_mock *Database) ListAllExecutions(ctx context.Context, filters db.TaskExecutionQueryFilter) ([]models.TaskExecution, error) {
	ret := _mock.Called(ctx, filters)

	if len(ret) == 0 {
		panic("no return value specified for ListAllExecutions")
	}

	var r0 []models.TaskExecution
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.TaskExecutionQueryFilter) ([]models.TaskExecution, error)); ok {
		return returnFunc(ctx, filters)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.TaskExecutionQueryFilter) []models.TaskExecution); ok {
		r0 = returnFunc(ctx, filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.TaskExecution)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, db.TaskExecutionQueryFilter) error); ok {
		r1 = returnFunc(ctx, filters)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Database_ListAllExecutions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAllExecutions'
type Database_ListAllExecutions_Call struct {
	*mock.Call
}

// ListAllExecutions is a helper method to define mock.On call
//   - ctx context.Context
//   - filters db.TaskExecutionQueryFilter
func (_e *Database_Expecter) ListAllExecutions(ctx interface{}, filters interface{}) *Database_ListAllExecutions_Call {
	return &Database_ListAllExecutions_Call{Call: _e.mock.On("ListAllExecutions", ctx, filters)}
}

func (_c *Database_ListAllExecutions_Call) Run(run func(ctx context.Context, filters db.TaskExecutionQueryFilter)) *Database_ListAllExecutions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 db.TaskExecutionQueryFilter
		if args[1] != nil {
			arg1 = args[1].(db.TaskExecutionQueryFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Database_ListAllExecutions_Call) Return(taskExecutions []models.TaskExecution, err error) *Database_ListAllExecutions_Call {
	_c.Call.Return(taskExecutions, err)
	return _c
}

func (_c *Database_ListAllExecutions_Call) RunAndReturn(run func(ctx context.Context, filters db.TaskExecutionQueryFilter) ([]models.TaskExecution, error)) *Database_ListAllExecutions_Call {
	_c.Call.Return(run)
	return _c
}

// ListSystemEvents provides a mock function for the type Database
func (_mock *Database) ListSystemEvents(ctx context.Context, filters db.SystemEventQueryFilter) ([]models.SystemEventAudit, error) {
	ret := _mock.Called(ctx, filters)

	if len(ret) == 0 {
		panic("no return value specified for ListSystemEvents")
	}

	var r0 []models.SystemEventAudit
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.SystemEventQueryFilter) ([]models.SystemEventAudit, error)); ok {
		return returnFunc(ctx, filters)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.SystemEventQueryFilter) []models.SystemEventAudit); ok {
		r0 = returnFunc(ctx, filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.SystemEventAudit)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, db.SystemEventQueryFilter) error); ok {
		r1 = returnFunc(ctx, filters)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Database_ListSystemEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSystemEvents'
type Database_ListSystemEvents_Call struct {
	*mock.Call
}

// ListSystemEvents is a helper method to define mock.On call
//   - ctx context.Context
//   - filters db.SystemEventQueryFilter
func (_e *Database_Expecter) ListSystemEvents(ctx interface{}, filters interface{}) *Database_ListSystemEvents_Call {
	return &Database_ListSystemEvents_Call{Call: _e.mock.On("ListSystemEvents", ctx, filters)}
}

func (_c *Database_ListSystemEvents_Call) Run(run func(ctx context.Context, filters db.SystemEventQueryFilter)) *Database_ListSystemEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 db.SystemEventQueryFilter
		if args[1] != nil {
			arg1 = args[1].(db.SystemEventQueryFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Database_ListSystemEvents_Call) Return(systemEventAudits []models.SystemEventAudit, err error) *Database_ListSystemEvents_Call {
	_c.Call.Return(systemEventAudits, err)
	return _c
}

func (_c *Database_ListSystemEvents_Call) RunAndReturn(run func(ctx context.Context, filters db.SystemEventQueryFilter) ([]models.SystemEventAudit, error)) *Database_ListSystemEvents_Call {
	_c.Call.Return(run)
	return _c
}

// ListTaskExecutions provides a mock function for the type Database
func (_mock *Database) ListTaskExecutions(ctx context.Context, taskID string, filters db.TaskExecutionQueryFilter) ([]models.TaskExecution, error) {
	ret := _mock.Called(ctx, taskID, filters)

	if len(ret) == 0 {
		panic("no return value specified for ListTaskExecutions")
	}

	var r0 []models.TaskExecution
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, db.TaskExecutionQueryFilter) ([]models.TaskExecution, error)); ok {
		return returnFunc(ctx, taskID, filters)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, db.TaskExecutionQueryFilter) []models.TaskExecution); ok {
		r0 = returnFunc(ctx, taskID, filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.TaskExecution)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, db.TaskExecutionQueryFilter) error); ok {
		r1 = returnFunc(ctx, taskID, filters)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Database_ListTaskExecutions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTaskExecutions'
type Database_ListTaskExecutions_Call struct {
	*mock.Call
}

// ListTaskExecutions is a helper method to define mock.On call
//   - ctx context.Context
//   - taskID string
//   - filters db.TaskExecutionQueryFilter
func (_e *Database_Expecter) ListTaskExecutions(ctx interface{}, taskID interface{}, filters interface{}) *Database_ListTaskExecutions_Call {
	return &Database_ListTaskExecutions_Call{Call: _e.mock.On("ListTaskExecutions", ctx, taskID, filters)}
}

func (_c *Database_ListTaskExecutions_Call) Run(run func(ctx context.Context, taskID string, filters db.TaskExecutionQueryFilter)) *Database_ListTaskExecutions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 db.TaskExecutionQueryFilter
		if args[2] != nil {
			arg2 = args[2].(db.TaskExecutionQueryFilter)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Database_ListTaskExecutions_Call) Return(taskExecutions []models.TaskExecution, err error) *Database_ListTaskExecutions_Call {
	_c.Call.Return(taskExecutions, err)
	return _c
}

func (_c *Database_ListTaskExecutions_Call) RunAndReturn(run func(ctx context.Context, taskID string, filters db.TaskExecutionQueryFilter) ([]models.TaskExecution, error)) *Database_ListTaskExecutions_Call {
	_c.Call.Return(run)
	return _c
}

// ListTasks provides a mock function for the type Database
func (_mock *Database) ListTasks(ctx context.Context, filters db.TaskQueryFilter) ([]models.Task, error) {
	ret := _mock.Called(ctx, filters)

	if len(ret) == 0 {
		panic("no return value specified for ListTasks")
	}

	var r0 []models.Task
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.TaskQueryFilter) ([]models.Task, error)); ok {
		return returnFunc(ctx, filters)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.TaskQueryFilter) []models.Task); ok {
		r0 = returnFunc(ctx, filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Task)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, db.TaskQueryFilter) error); ok {
		r1 = returnFunc(ctx, filters)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Database_ListTasks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTasks'
type Database_ListTasks_Call struct {
	*mock.Call
}

// ListTasks is a helper method to define mock.On call
//   - ctx context.Context
//   - filters db.TaskQueryFilter
func (_e *Database_Expecter) ListTasks(ctx interface{}, filters interface{}) *Database_ListTasks_Call {
	return &Database_ListTasks_Call{Call: _e.mock.On("ListTasks", ctx, filters)}
}

func (_c *Database_ListTasks_Call) Run(run func(ctx context.Context, filters db.TaskQueryFilter)) *Database_ListTasks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 db.TaskQueryFilter
		if args[1] != nil {
			arg1 = args[1].(db.TaskQueryFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Database_ListTasks_Call) Return(tasks []models.Task, err error) *Database_ListTasks_Call {
	_c.Call.Return(tasks, err)
	return _c
}

func (_c *Database_ListTasks_Call) RunAndReturn(run func(ctx context.Context, filters db.TaskQueryFilter) ([]models.Task, error)) *Database_ListTasks_Call {
	_c.Call.Return(run)
	return _c
}

// MarkTaskActive provides a mock function for the type Database
func (_mock *Database) MarkTaskActive(ctx context.Context, taskID string) error {
	ret := _mock.Called(ctx, taskID)

	if len(ret) == 0 {
		panic("no return value specified for MarkTaskActive")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, taskID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Database_MarkTaskActive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkTaskActive'
type Database_MarkTaskActive_Call struct {
	*mock.Call
}

// MarkTaskActive is a helper method to define mock.On call
//   - ctx context.Context
//   - taskID string
func (_e *Database_Expecter) MarkTaskActive(ctx interface{}, taskID interface{}) *Database_MarkTaskActive_Call {
	return &Database_MarkTaskActive_Call{Call: _e.mock.On("MarkTaskActive", ctx, taskID)}
}

func (_c *Database_MarkTaskActive_Call) Run(run func(ctx context.Context, taskID string)) *Database_MarkTaskActive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Database_MarkTaskActive_Call) Return(err error) *Database_MarkTaskActive_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Database_MarkTaskActive_Call) RunAndReturn(run func(ctx context.Context, taskID string) error) *Database_MarkTaskActive_Call {
	_c.Call.Return(run)
	return _c
}

// MarkTaskCancelled provides a mock function for the type Database
func (_mock *Database) MarkTaskCancelled(ctx context.Context, taskID string) error {
	ret := _mock.Called(ctx, taskID)

	if len(ret) == 0 {
		panic("no return value specified for MarkTaskCancelled")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, taskID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Database_MarkTaskCancelled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkTaskCancelled'
type Database_MarkTaskCancelled_Call struct {
	*mock.Call
}

// MarkTaskCancelled is a helper method to define mock.On call
//   - ctx context.Context
//   - taskID string
func (_e *Database_Expecter) MarkTaskCancelled(ctx interface{}, taskID interface{}) *Database_MarkTaskCancelled_Call {
	return &Database_MarkTaskCancelled_Call{Call: _e.mock.On("MarkTaskCancelled", ctx, taskID)}
}

func (_c *Database_MarkTaskCancelled_Call) Run(run func(ctx context.Context, taskID string)) *Database_MarkTaskCancelled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Database_MarkTaskCancelled_Call) Return(err error) *Database_MarkTaskCancelled_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Database_MarkTaskCancelled_Call) RunAndReturn(run func(ctx context.Context, taskID string) error) *Database_MarkTaskCancelled_Call {
	_c.Call.Return(run)
	return _c
}

// MarkTaskCancelling provides a mock function for the type Database
func (_mock *Database) MarkTaskCancelling(ctx context.Context, taskID string) error {
	ret := _mock.Called(ctx, taskID)

	if len(ret) == 0 {
		panic("no return value specified for MarkTaskCancelling")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, taskID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Database_MarkTaskCancelling_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkTaskCancelling'
type Database_MarkTaskCancelling_Call struct {
	*mock.Call
}

// MarkTaskCancelling is a helper method to define mock.On call
//   - ctx context.Context
//   - taskID string
func (_e *Database_Expecter) MarkTaskCancelling(ctx interface{}, taskID interface{}) *Database_MarkTaskCancelling_Call {
	return &Database_MarkTaskCancelling_Call{Call: _e.mock.On("MarkTaskCancelling", ctx, taskID)}
}

func (_c *Database_MarkTaskCancelling_Call) Run(run func(ctx context.Context, taskID string)) *Database_MarkTaskCancelling_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Database_MarkTaskCancelling_Call) Return(err error) *Database_MarkTaskCancelling_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Database_MarkTaskCancelling_Call) RunAndReturn(run func(ctx context.Context, taskID string) error) *Database_MarkTaskCancelling_Call {
	_c.Call.Return(run)
	return _c
}

// MarkTaskComplete provides a mock function for the type Database
func (_mock *Database) MarkTaskComplete(ctx context.Context, taskID string) error {
	ret := _mock.Called(ctx, taskID)

	if len(ret) == 0 {
		panic("no return value specified for MarkTaskComplete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, taskID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Database_MarkTaskComplete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkTaskComplete'
type Database_MarkTaskComplete_Call struct {
	*mock.Call
}

// MarkTaskComplete is a helper method to define mock.On call
//   - ctx context.Context
//   - taskID string
func (_e *Database_Expecter) MarkTaskComplete(ctx interface{}, taskID interface{}) *Database_MarkTaskComplete_Call {
	return &Database_MarkTaskComplete_Call{Call: _e.mock.On("MarkTaskComplete", ctx, taskID)}
}

func (_c *Database_MarkTaskComplete_Call) Run(run func(ctx context.Context, taskID string)) *Database_MarkTaskComplete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Database_MarkTaskComplete_Call) Return(err error) *Database_MarkTaskComplete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Database_MarkTaskComplete_Call) RunAndReturn(run func(ctx context.Context, taskID string) error) *Database_MarkTaskComplete_Call {
	_c.Call.Return(run)
	return _c
}

// MarkTaskExecAcquired provides a mock function for the type Database
func (_mock *Database) MarkTaskExecAcquired(ctx context.Context, instanceID string, workerName string) error {
	ret := _mock.Called(ctx, instanceID, workerName)

	if len(ret) == 0 {
		panic("no return value specified for MarkTaskExecAcquired")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, instanceID, workerName)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Database_MarkTaskExecAcquired_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkTaskExecAcquired'
type Database_MarkTaskExecAcquired_Call struct {
	*mock.Call
}

// MarkTaskExecAcquired is a helper method to define mock.On call
//   - ctx context.Context
//   - instanceID string
//   - workerName string
func (_e *Database_Expecter) MarkTaskExecAcquired(ctx interface{}, instanceID interface{}, workerName interface{}) *Database_MarkTaskExecAcquired_Call {
	return &Database_MarkTaskExecAcquired_Call{Call: _e.mock.On("MarkTaskExecAcquired", ctx, instanceID, workerName)}
}

func (_c *Database_MarkTaskExecAcquired_Call) Run(run func(ctx context.Context, instanceID string, workerName string)) *Database_MarkTaskExecAcquired_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Database_MarkTaskExecAcquired_Call) Return(err error) *Database_MarkTaskExecAcquired_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Database_MarkTaskExecAcquired_Call) RunAndReturn(run func(ctx context.Context, instanceID string, workerName string) error) *Database_MarkTaskExecAcquired_Call {
	_c.Call.Return(run)
	return _c
}

// MarkTaskExecCancelled provides a mock function for the type Database
func (_mock *Database) MarkTaskExecCancelled(ctx context.Context, instanceID string, cancelMsg string) error {
	ret := _mock.Called(ctx, instanceID, cancelMsg)

	if len(ret) == 0 {
		panic("no return value specified for MarkTaskExecCancelled")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, instanceID, cancelMsg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Database_MarkTaskExecCancelled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkTaskExecCancelled'
type Database_MarkTaskExecCancelled_Call struct {
	*mock.Call
}

// MarkTaskExecCancelled is a helper method to define mock.On call
//   - ctx context.Context
//   - instanceID string
//   - cancelMsg string
func (_e *Database_Expecter) MarkTaskExecCancelled(ctx interface{}, instanceID interface{}, cancelMsg interface{}) *Database_MarkTaskExecCancelled_Call {
	return &Database_MarkTaskExecCancelled_Call{Call: _e.mock.On("MarkTaskExecCancelled", ctx, instanceID, cancelMsg)}
}

func (_c *Database_MarkTaskExecCancelled_Call) Run(run func(ctx context.Context, instanceID string, cancelMsg string)) *Database_MarkTaskExecCancelled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Database_MarkTaskExecCancelled_Call) Return(err error) *Database_MarkTaskExecCancelled_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Database_MarkTaskExecCancelled_Call) RunAndReturn(run func(ctx context.Context, instanceID string, cancelMsg string) error) *Database_MarkTaskExecCancelled_Call {
	_c.Call.Return(run)
	return _c
}

// MarkTaskExecFailed provides a mock function for the type Database
func (_mock *Database) MarkTaskExecFailed(ctx context.Context, instanceID string, errorMsg string) error {
	ret := _mock.Called(ctx, instanceID, errorMsg)

	if len(ret) == 0 {
		panic("no return value specified for MarkTaskExecFailed")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, instanceID, errorMsg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Database_MarkTaskExecFailed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkTaskExecFailed'
type Database_MarkTaskExecFailed_Call struct {
	*mock.Call
}

// MarkTaskExecFailed is a helper method to define mock.On call
//   - ctx context.Context
//   - instanceID string
//   - errorMsg string
func (_e *Database_Expecter) MarkTaskExecFailed(ctx interface{}, instanceID interface{}, errorMsg interface{}) *Database_MarkTaskExecFailed_Call {
	return &Database_MarkTaskExecFailed_Call{Call: _e.mock.On("MarkTaskExecFailed", ctx, instanceID, errorMsg)}
}

func (_c *Database_MarkTaskExecFailed_Call) Run(run func(ctx context.Context, instanceID string, errorMsg string)) *Database_MarkTaskExecFailed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Database_MarkTaskExecFailed_Call) Return(err error) *Database_MarkTaskExecFailed_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Database_MarkTaskExecFailed_Call) RunAndReturn(run func(ctx context.Context, instanceID string, errorMsg string) error) *Database_MarkTaskExecFailed_Call {
	_c.Call.Return(run)
	return _c
}

// MarkTaskExecFinalized provides a mock function for the type Database
func (_mock *Database) MarkTaskExecFinalized(ctx context.Context, instanceID string) error {
	ret := _mock.Called(ctx, instanceID)

	if len(ret) == 0 {
		panic("no return value specified for MarkTaskExecFinalized")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, instanceID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Database_MarkTaskExecFinalized_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkTaskExecFinalized'
type Database_MarkTaskExecFinalized_Call struct {
	*mock.Call
}

// MarkTaskExecFinalized is a helper method to define mock.On call
//   - ctx context.Context
//   - instanceID string
func (_e *Database_Expecter) MarkTaskExecFinalized(ctx interface{}, instanceID interface{}) *Database_MarkTaskExecFinalized_Call {
	return &Database_MarkTaskExecFinalized_Call{Call: _e.mock.On("MarkTaskExecFinalized", ctx, instanceID)}
}

func (_c *Database_MarkTaskExecFinalized_Call) Run(run func(ctx context.Context, instanceID string)) *Database_MarkTaskExecFinalized_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Database_MarkTaskExecFinalized_Call) Return(err error) *Database_MarkTaskExecFinalized_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Database_MarkTaskExecFinalized_Call) RunAndReturn(run func(ctx context.Context, instanceID string) error) *Database_MarkTaskExecFinalized_Call {
	_c.Call.Return(run)
	return _c
}

// MarkTaskExecProcessed provides a mock function for the type Database
func (_mock *Database) MarkTaskExecProcessed(ctx context.Context, instanceID string) error {
	ret := _mock.Called(ctx, instanceID)

	if len(ret) == 0 {
		panic("no return value specified for MarkTaskExecProcessed")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, instanceID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Database_MarkTaskExecProcessed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkTaskExecProcessed'
type Database_MarkTaskExecProcessed_Call struct {
	*mock.Call
}

// MarkTaskExecProcessed is a helper method to define mock.On call
//   - ctx context.Context
//   - instanceID string
func (_e *Database_Expecter) MarkTaskExecProcessed(ctx interface{}, instanceID interface{}) *Database_MarkTaskExecProcessed_Call {
	return &Database_MarkTaskExecProcessed_Call{Call: _e.mock.On("MarkTaskExecProcessed", ctx, instanceID)}
}

func (_c *Database_MarkTaskExecProcessed_Call) Run(run func(ctx context.Context, instanceID string)) *Database_MarkTaskExecProcessed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Database_MarkTaskExecProcessed_Call) Return(err error) *Database_MarkTaskExecProcessed_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Database_MarkTaskExecProcessed_Call) RunAndReturn(run func(ctx context.Context, instanceID string) error) *Database_MarkTaskExecProcessed_Call {
	_c.Call.Return(run)
	return _c
}

// MarkTaskExecProcessing provides a mock function for the type Database
func (_mock *Database) MarkTaskExecProcessing(ctx context.Context, instanceID string) error {
	ret := _mock.Called(ctx, instanceID)

	if len(ret) == 0 {
		panic("no return value specified for MarkTaskExecProcessing")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, instanceID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Database_MarkTaskExecProcessing_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkTaskExecProcessing'
type Database_MarkTaskExecProcessing_Call struct {
	*mock.Call
}

// MarkTaskExecProcessing is a helper method to define mock.On call
//   - ctx context.Context
//   - instanceID string
func (_e *Database_Expecter) MarkTaskExecProcessing(ctx interface{}, instanceID interface{}) *Database_MarkTaskExecProcessing_Call {
	return &Database_MarkTaskExecProcessing_Call{Call: _e.mock.On("MarkTaskExecProcessing", ctx, instanceID)}
}

func (_c *Database_MarkTaskExecProcessing_Call) Run(run func(ctx context.Context, instanceID string)) *Database_MarkTaskExecProcessing_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Database_MarkTaskExecProcessing_Call) Return(err error) *Database_MarkTaskExecProcessing_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Database_MarkTaskExecProcessing_Call) RunAndReturn(run func(ctx context.Context, instanceID string) error) *Database_MarkTaskExecProcessing_Call {
	_c.Call.Return(run)
	return _c
}

// MarkTaskExecQueued provides a mock function for the type Database
func (_mock *Database) MarkTaskExecQueued(ctx context.Context, instanceID string) error {
	ret := _mock.Called(ctx, instanceID)

	if len(ret) == 0 {
		panic("no return value specified for MarkTaskExecQueued")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, instanceID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Database_MarkTaskExecQueued_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkTaskExecQueued'
type Database_MarkTaskExecQueued_Call struct {
	*mock.Call
}

// MarkTaskExecQueued is a helper method to define mock.On call
//   - ctx context.Context
//   - instanceID string
func (_e *Database_Expecter) MarkTaskExecQueued(ctx interface{}, instanceID interface{}) *Database_MarkTaskExecQueued_Call {
	return &Database_MarkTaskExecQueued_Call{Call: _e.mock.On("MarkTaskExecQueued", ctx, instanceID)}
}

func (_c *Database_MarkTaskExecQueued_Call) Run(run func(ctx context.Context, instanceID string)) *Database_MarkTaskExecQueued_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Database_MarkTaskExecQueued_Call) Return(err error) *Database_MarkTaskExecQueued_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Database_MarkTaskExecQueued_Call) RunAndReturn(run func(ctx context.Context, instanceID string) error) *Database_MarkTaskExecQueued_Call {
	_c.Call.Return(run)
	return _c
}

// MarkTaskFailed provides a mock function for the type Database
func (_mock *Database) MarkTaskFailed(ctx context.Context, taskID string) error {
	ret := _mock.Called(ctx, taskID)

	if len(ret) == 0 {
		panic("no return value specified for MarkTaskFailed")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, taskID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Database_MarkTaskFailed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkTaskFailed'
type Database_MarkTaskFailed_Call struct {
	*mock.Call
}

// MarkTaskFailed is a helper method to define mock.On call
//   - ctx context.Context
//   - taskID string
func (_e *Database_Expecter) MarkTaskFailed(ctx interface{}, taskID interface{}) *Database_MarkTaskFailed_Call {
	return &Database_MarkTaskFailed_Call{Call: _e.mock.On("MarkTaskFailed", ctx, taskID)}
}

func (_c *Database_MarkTaskFailed_Call) Run(run func(ctx context.Context, taskID string)) *Database_MarkTaskFailed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Database_MarkTaskFailed_Call) Return(err error) *Database_MarkTaskFailed_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Database_MarkTaskFailed_Call) RunAndReturn(run func(ctx context.Context, taskID string) error) *Database_MarkTaskFailed_Call {
	_c.Call.Return(run)
	return _c
}

// MarkTaskTimedOut provides a mock function for the type Database
func (_mock *Database) MarkTaskTimedOut(ctx context.Context, taskID string) error {
	ret := _mock.Called(ctx, taskID)

	if len(ret) == 0 {
		panic("no return value specified for MarkTaskTimedOut")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, taskID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Database_MarkTaskTimedOut_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkTaskTimedOut'
type Database_MarkTaskTimedOut_Call struct {
	*mock.Call
}

// MarkTaskTimedOut is a helper method to define mock.On call
//   - ctx context.Context
//   - taskID string
func (_e *Database_Expecter) MarkTaskTimedOut(ctx interface{}, taskID interface{}) *Database_MarkTaskTimedOut_Call {
	return &Database_MarkTaskTimedOut_Call{Call: _e.mock.On("MarkTaskTimedOut", ctx, taskID)}
}

func (_c *Database_MarkTaskTimedOut_Call) Run(run func(ctx context.Context, taskID string)) *Database_MarkTaskTimedOut_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Database_MarkTaskTimedOut_Call) Return(err error) *Database_MarkTaskTimedOut_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Database_MarkTaskTimedOut_Call) RunAndReturn(run func(ctx context.Context, taskID string) error) *Database_MarkTaskTimedOut_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTaskDeadline provides a mock function for the type Database
func (_mock *Database) UpdateTaskDeadline(ctx context.Context, taskID string, deadline time.Time) error {
	ret := _mock.Called(ctx, taskID, deadline)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTaskDeadline")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time) error); ok {
		r0 = returnFunc(ctx, taskID, deadline)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Database_UpdateTaskDeadline_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTaskDeadline'
type Database_UpdateTaskDeadline_Call struct {
	*mock.Call
}

// UpdateTaskDeadline is a helper method to define mock.On call
//   - ctx context.Context
//   - taskID string
//   - deadline time.Time
func (_e *Database_Expecter) UpdateTaskDeadline(ctx interface{}, taskID interface{}, deadline interface{}) *Database_UpdateTaskDeadline_Call {
	return &Database_UpdateTaskDeadline_Call{Call: _e.mock.On("UpdateTaskDeadline", ctx, taskID, deadline)}
}

func (_c *Database_UpdateTaskDeadline_Call) Run(run func(ctx context.Context, taskID string, deadline time.Time)) *Database_UpdateTaskDeadline_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Database_UpdateTaskDeadline_Call) Return(err error) *Database_UpdateTaskDeadline_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Database_UpdateTaskDeadline_Call) RunAndReturn(run func(ctx context.Context, taskID string, deadline time.Time) error) *Database_UpdateTaskDeadline_Call {
	_c.Call.Return(run)
	return _c
}
