// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocktest

import (
	"context"
	"time"

	"github.com/alwitt/goutils/redis"
	mock "github.com/stretchr/testify/mock"
)

// NewRedisQueueForTest creates a new instance of RedisQueueForTest. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRedisQueueForTest(t interface {
	mock.TestingT
	Cleanup(func())
}) *RedisQueueForTest {
	mock := &RedisQueueForTest{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// RedisQueueForTest is an autogenerated mock type for the RedisQueueForTest type
type RedisQueueForTest struct {
	mock.Mock
}

type RedisQueueForTest_Expecter struct {
	mock *mock.Mock
}

func (_m *RedisQueueForTest) EXPECT() *RedisQueueForTest_Expecter {
	return &RedisQueueForTest_Expecter{mock: &_m.Mock}
}

// Length provides a mock function for the type RedisQueueForTest
func (_mock *RedisQueueForTest) Length(ctx context.Context) (uint64, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Length")
	}

	var r0 uint64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (uint64, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) uint64); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(uint64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RedisQueueForTest_Length_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Length'
type RedisQueueForTest_Length_Call struct {
	*mock.Call
}

// Length is a helper method to define mock.On call
//   - ctx context.Context
func (_e *RedisQueueForTest_Expecter) Length(ctx interface{}) *RedisQueueForTest_Length_Call {
	return &RedisQueueForTest_Length_Call{Call: _e.mock.On("Length", ctx)}
}

func (_c *RedisQueueForTest_Length_Call) Run(run func(ctx context.Context)) *RedisQueueForTest_Length_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *RedisQueueForTest_Length_Call) Return(v uint64, err error) *RedisQueueForTest_Length_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *RedisQueueForTest_Length_Call) RunAndReturn(run func(ctx context.Context) (uint64, error)) *RedisQueueForTest_Length_Call {
	_c.Call.Return(run)
	return _c
}

// PeakLeft provides a mock function for the type RedisQueueForTest
func (_mock *RedisQueueForTest) PeakLeft(ctx context.Context) (redis.QueueMessageEnvelope, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for PeakLeft")
	}

	var r0 redis.QueueMessageEnvelope
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (redis.QueueMessageEnvelope, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) redis.QueueMessageEnvelope); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(redis.QueueMessageEnvelope)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RedisQueueForTest_PeakLeft_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PeakLeft'
type RedisQueueForTest_PeakLeft_Call struct {
	*mock.Call
}

// PeakLeft is a helper method to define mock.On call
//   - ctx context.Context
func (_e *RedisQueueForTest_Expecter) PeakLeft(ctx interface{}) *RedisQueueForTest_PeakLeft_Call {
	return &RedisQueueForTest_PeakLeft_Call{Call: _e.mock.On("PeakLeft", ctx)}
}

func (_c *RedisQueueForTest_PeakLeft_Call) Run(run func(ctx context.Context)) *RedisQueueForTest_PeakLeft_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *RedisQueueForTest_PeakLeft_Call) Return(queueMessageEnvelope redis.QueueMessageEnvelope, err error) *RedisQueueForTest_PeakLeft_Call {
	_c.Call.Return(queueMessageEnvelope, err)
	return _c
}

func (_c *RedisQueueForTest_PeakLeft_Call) RunAndReturn(run func(ctx context.Context) (redis.QueueMessageEnvelope, error)) *RedisQueueForTest_PeakLeft_Call {
	_c.Call.Return(run)
	return _c
}

// PeakRight provides a mock function for the type RedisQueueForTest
func (_mock *RedisQueueForTest) PeakRight(ctx context.Context) (redis.QueueMessageEnvelope, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for PeakRight")
	}

	var r0 redis.QueueMessageEnvelope
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (redis.QueueMessageEnvelope, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) redis.QueueMessageEnvelope); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(redis.QueueMessageEnvelope)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RedisQueueForTest_PeakRight_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PeakRight'
type RedisQueueForTest_PeakRight_Call struct {
	*mock.Call
}

// PeakRight is a helper method to define mock.On call
//   - ctx context.Context
func (_e *RedisQueueForTest_Expecter) PeakRight(ctx interface{}) *RedisQueueForTest_PeakRight_Call {
	return &RedisQueueForTest_PeakRight_Call{Call: _e.mock.On("PeakRight", ctx)}
}

func (_c *RedisQueueForTest_PeakRight_Call) Run(run func(ctx context.Context)) *RedisQueueForTest_PeakRight_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *RedisQueueForTest_PeakRight_Call) Return(queueMessageEnvelope redis.QueueMessageEnvelope, err error) *RedisQueueForTest_PeakRight_Call {
	_c.Call.Return(queueMessageEnvelope, err)
	return _c
}

func (_c *RedisQueueForTest_PeakRight_Call) RunAndReturn(run func(ctx context.Context) (redis.QueueMessageEnvelope, error)) *RedisQueueForTest_PeakRight_Call {
	_c.Call.Return(run)
	return _c
}

// PopLeft provides a mock function for the type RedisQueueForTest
func (_mock *RedisQueueForTest) PopLeft(ctx context.Context, blocking bool, maxWait *time.Duration) (redis.QueueMessageEnvelope, error) {
	ret := _mock.Called(ctx, blocking, maxWait)

	if len(ret) == 0 {
		panic("no return value specified for PopLeft")
	}

	var r0 redis.QueueMessageEnvelope
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, bool, *time.Duration) (redis.QueueMessageEnvelope, error)); ok {
		return returnFunc(ctx, blocking, maxWait)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, bool, *time.Duration) redis.QueueMessageEnvelope); ok {
		r0 = returnFunc(ctx, blocking, maxWait)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(redis.QueueMessageEnvelope)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, bool, *time.Duration) error); ok {
		r1 = returnFunc(ctx, blocking, maxWait)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RedisQueueForTest_PopLeft_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PopLeft'
type RedisQueueForTest_PopLeft_Call struct {
	*mock.Call
}

// PopLeft is a helper method to define mock.On call
//   - ctx context.Context
//   - blocking bool
//   - maxWait *time.Duration
func (_e *RedisQueueForTest_Expecter) PopLeft(ctx interface{}, blocking interface{}, maxWait interface{}) *RedisQueueForTest_PopLeft_Call {
	return &RedisQueueForTest_PopLeft_Call{Call: _e.mock.On("PopLeft", ctx, blocking, maxWait)}
}

func (_c *RedisQueueForTest_PopLeft_Call) Run(run func(ctx context.Context, blocking bool, maxWait *time.Duration)) *RedisQueueForTest_PopLeft_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 bool
		if args[1] != nil {
			arg1 = args[1].(bool)
		}
		var arg2 *time.Duration
		if args[2] != nil {
			arg2 = args[2].(*time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *RedisQueueForTest_PopLeft_Call) Return(queueMessageEnvelope redis.QueueMessageEnvelope, err error) *RedisQueueForTest_PopLeft_Call {
	_c.Call.Return(queueMessageEnvelope, err)
	return _c
}

func (_c *RedisQueueForTest_PopLeft_Call) RunAndReturn(run func(ctx context.Context, blocking bool, maxWait *time.Duration) (redis.QueueMessageEnvelope, error)) *RedisQueueForTest_PopLeft_Call {
	_c.Call.Return(run)
	return _c
}

// PopLeftAndMove provides a mock function for the type RedisQueueForTest
func (_mock *RedisQueueForTest) PopLeftAndMove(ctx context.Context, destination string, insertOnLeft bool, blocking bool, maxWait *time.Duration) (redis.QueueMessageEnvelope, error) {
	ret := _mock.Called(ctx, destination, insertOnLeft, blocking, maxWait)

	if len(ret) == 0 {
		panic("no return value specified for PopLeftAndMove")
	}

	var r0 redis.QueueMessageEnvelope
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, bool, bool, *time.Duration) (redis.QueueMessageEnvelope, error)); ok {
		return returnFunc(ctx, destination, insertOnLeft, blocking, maxWait)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, bool, bool, *time.Duration) redis.QueueMessageEnvelope); ok {
		r0 = returnFunc(ctx, destination, insertOnLeft, blocking, maxWait)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(redis.QueueMessageEnvelope)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, bool, bool, *time.Duration) error); ok {
		r1 = returnFunc(ctx, destination, insertOnLeft, blocking, maxWait)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RedisQueueForTest_PopLeftAndMove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PopLeftAndMove'
type RedisQueueForTest_PopLeftAndMove_Call struct {
	*mock.Call
}

// PopLeftAndMove is a helper method to define mock.On call
//   - ctx context.Context
//   - destination string
//   - insertOnLeft bool
//   - blocking bool
//   - maxWait *time.Duration
func (_e *RedisQueueForTest_Expecter) PopLeftAndMove(ctx interface{}, destination interface{}, insertOnLeft interface{}, blocking interface{}, maxWait interface{}) *RedisQueueForTest_PopLeftAndMove_Call {
	return &RedisQueueForTest_PopLeftAndMove_Call{Call: _e.mock.On("PopLeftAndMove", ctx, destination, insertOnLeft, blocking, maxWait)}
}

func (_c *RedisQueueForTest_PopLeftAndMove_Call) Run(run func(ctx context.Context, destination string, insertOnLeft bool, blocking bool, maxWait *time.Duration)) *RedisQueueForTest_PopLeftAndMove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		var arg4 *time.Duration
		if args[4] != nil {
			arg4 = args[4].(*time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *RedisQueueForTest_PopLeftAndMove_Call) Return(queueMessageEnvelope redis.QueueMessageEnvelope, err error) *RedisQueueForTest_PopLeftAndMove_Call {
	_c.Call.Return(queueMessageEnvelope, err)
	return _c
}

func (_c *RedisQueueForTest_PopLeftAndMove_Call) RunAndReturn(run func(ctx context.Context, destination string, insertOnLeft bool, blocking bool, maxWait *time.Duration) (redis.QueueMessageEnvelope, error)) *RedisQueueForTest_PopLeftAndMove_Call {
	_c.Call.Return(run)
	return _c
}

// PopRight provides a mock function for the type RedisQueueForTest
func (_mock *RedisQueueForTest) PopRight(ctx context.Context, blocking bool, maxWait *time.Duration) (redis.QueueMessageEnvelope, error) {
	ret := _mock.Called(ctx, blocking, maxWait)

	if len(ret) == 0 {
		panic("no return value specified for PopRight")
	}

	var r0 redis.QueueMessageEnvelope
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, bool, *time.Duration) (redis.QueueMessageEnvelope, error)); ok {
		return returnFunc(ctx, blocking, maxWait)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, bool, *time.Duration) redis.QueueMessageEnvelope); ok {
		r0 = returnFunc(ctx, blocking, maxWait)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(redis.QueueMessageEnvelope)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, bool, *time.Duration) error); ok {
		r1 = returnFunc(ctx, blocking, maxWait)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RedisQueueForTest_PopRight_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PopRight'
type RedisQueueForTest_PopRight_Call struct {
	*mock.Call
}

// PopRight is a helper method to define mock.On call
//   - ctx context.Context
//   - blocking bool
//   - maxWait *time.Duration
func (_e *RedisQueueForTest_Expecter) PopRight(ctx interface{}, blocking interface{}, maxWait interface{}) *RedisQueueForTest_PopRight_Call {
	return &RedisQueueForTest_PopRight_Call{Call: _e.mock.On("PopRight", ctx, blocking, maxWait)}
}

func (_c *RedisQueueForTest_PopRight_Call) Run(run func(ctx context.Context, blocking bool, maxWait *time.Duration)) *RedisQueueForTest_PopRight_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 bool
		if args[1] != nil {
			arg1 = args[1].(bool)
		}
		var arg2 *time.Duration
		if args[2] != nil {
			arg2 = args[2].(*time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *RedisQueueForTest_PopRight_Call) Return(queueMessageEnvelope redis.QueueMessageEnvelope, err error) *RedisQueueForTest_PopRight_Call {
	_c.Call.Return(queueMessageEnvelope, err)
	return _c
}

func (_c *RedisQueueForTest_PopRight_Call) RunAndReturn(run func(ctx context.Context, blocking bool, maxWait *time.Duration) (redis.QueueMessageEnvelope, error)) *RedisQueueForTest_PopRight_Call {
	_c.Call.Return(run)
	return _c
}

// PopRightAndMove provides a mock function for the type RedisQueueForTest
func (_mock *RedisQueueForTest) PopRightAndMove(ctx context.Context, destination string, insertOnLeft bool, blocking bool, maxWait *time.Duration) (redis.QueueMessageEnvelope, error) {
	ret := _mock.Called(ctx, destination, insertOnLeft, blocking, maxWait)

	if len(ret) == 0 {
		panic("no return value specified for PopRightAndMove")
	}

	var r0 redis.QueueMessageEnvelope
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, bool, bool, *time.Duration) (redis.QueueMessageEnvelope, error)); ok {
		return returnFunc(ctx, destination, insertOnLeft, blocking, maxWait)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, bool, bool, *time.Duration) redis.QueueMessageEnvelope); ok {
		r0 = returnFunc(ctx, destination, insertOnLeft, blocking, maxWait)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(redis.QueueMessageEnvelope)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, bool, bool, *time.Duration) error); ok {
		r1 = returnFunc(ctx, destination, insertOnLeft, blocking, maxWait)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RedisQueueForTest_PopRightAndMove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PopRightAndMove'
type RedisQueueForTest_PopRightAndMove_Call struct {
	*mock.Call
}

// PopRightAndMove is a helper method to define mock.On call
//   - ctx context.Context
//   - destination string
//   - insertOnLeft bool
//   - blocking bool
//   - maxWait *time.Duration
func (_e *RedisQueueForTest_Expecter) PopRightAndMove(ctx interface{}, destination interface{}, insertOnLeft interface{}, blocking interface{}, maxWait interface{}) *RedisQueueForTest_PopRightAndMove_Call {
	return &RedisQueueForTest_PopRightAndMove_Call{Call: _e.mock.On("PopRightAndMove", ctx, destination, insertOnLeft, blocking, maxWait)}
}

func (_c *RedisQueueForTest_PopRightAndMove_Call) Run(run func(ctx context.Context, destination string, insertOnLeft bool, blocking bool, maxWait *time.Duration)) *RedisQueueForTest_PopRightAndMove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		var arg4 *time.Duration
		if args[4] != nil {
			arg4 = args[4].(*time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *RedisQueueForTest_PopRightAndMove_Call) Return(queueMessageEnvelope redis.QueueMessageEnvelope, err error) *RedisQueueForTest_PopRightAndMove_Call {
	_c.Call.Return(queueMessageEnvelope, err)
	return _c
}

func (_c *RedisQueueForTest_PopRightAndMove_Call) RunAndReturn(run func(ctx context.Context, destination string, insertOnLeft bool, blocking bool, maxWait *time.Duration) (redis.QueueMessageEnvelope, error)) *RedisQueueForTest_PopRightAndMove_Call {
	_c.Call.Return(run)
	return _c
}

// PushLeft provides a mock function for the type RedisQueueForTest
func (_mock *RedisQueueForTest) PushLeft(ctx context.Context, message redis.QueueMessageEnvelope, ttl *time.Duration) (uint64, error) {
	ret := _mock.Called(ctx, message, ttl)

	if len(ret) == 0 {
		panic("no return value specified for PushLeft")
	}

	var r0 uint64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, redis.QueueMessageEnvelope, *time.Duration) (uint64, error)); ok {
		return returnFunc(ctx, message, ttl)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, redis.QueueMessageEnvelope, *time.Duration) uint64); ok {
		r0 = returnFunc(ctx, message, ttl)
	} else {
		r0 = ret.Get(0).(uint64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, redis.QueueMessageEnvelope, *time.Duration) error); ok {
		r1 = returnFunc(ctx, message, ttl)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RedisQueueForTest_PushLeft_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PushLeft'
type RedisQueueForTest_PushLeft_Call struct {
	*mock.Call
}

// PushLeft is a helper method to define mock.On call
//   - ctx context.Context
//   - message redis.QueueMessageEnvelope
//   - ttl *time.Duration
func (_e *RedisQueueForTest_Expecter) PushLeft(ctx interface{}, message interface{}, ttl interface{}) *RedisQueueForTest_PushLeft_Call {
	return &RedisQueueForTest_PushLeft_Call{Call: _e.mock.On("PushLeft", ctx, message, ttl)}
}

func (_c *RedisQueueForTest_PushLeft_Call) Run(run func(ctx context.Context, message redis.QueueMessageEnvelope, ttl *time.Duration)) *RedisQueueForTest_PushLeft_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 redis.QueueMessageEnvelope
		if args[1] != nil {
			arg1 = args[1].(redis.QueueMessageEnvelope)
		}
		var arg2 *time.Duration
		if args[2] != nil {
			arg2 = args[2].(*time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *RedisQueueForTest_PushLeft_Call) Return(v uint64, err error) *RedisQueueForTest_PushLeft_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *RedisQueueForTest_PushLeft_Call) RunAndReturn(run func(ctx context.Context, message redis.QueueMessageEnvelope, ttl *time.Duration) (uint64, error)) *RedisQueueForTest_PushLeft_Call {
	_c.Call.Return(run)
	return _c
}

// PushRight provides a mock function for the type RedisQueueForTest
func (_mock *RedisQueueForTest) PushRight(ctx context.Context, message redis.QueueMessageEnvelope, ttl *time.Duration) (uint64, error) {
	ret := _mock.Called(ctx, message, ttl)

	if len(ret) == 0 {
		panic("no return value specified for PushRight")
	}

	var r0 uint64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, redis.QueueMessageEnvelope, *time.Duration) (uint64, error)); ok {
		return returnFunc(ctx, message, ttl)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, redis.QueueMessageEnvelope, *time.Duration) uint64); ok {
		r0 = returnFunc(ctx, message, ttl)
	} else {
		r0 = ret.Get(0).(uint64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, redis.QueueMessageEnvelope, *time.Duration) error); ok {
		r1 = returnFunc(ctx, message, ttl)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RedisQueueForTest_PushRight_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PushRight'
type RedisQueueForTest_PushRight_Call struct {
	*mock.Call
}

// PushRight is a helper method to define mock.On call
//   - ctx context.Context
//   - message redis.QueueMessageEnvelope
//   - ttl *time.Duration
func (_e *RedisQueueForTest_Expecter) PushRight(ctx interface{}, message interface{}, ttl interface{}) *RedisQueueForTest_PushRight_Call {
	return &RedisQueueForTest_PushRight_Call{Call: _e.mock.On("PushRight", ctx, message, ttl)}
}

func (_c *RedisQueueForTest_PushRight_Call) Run(run func(ctx context.Context, message redis.QueueMessageEnvelope, ttl *time.Duration)) *RedisQueueForTest_PushRight_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 redis.QueueMessageEnvelope
		if args[1] != nil {
			arg1 = args[1].(redis.QueueMessageEnvelope)
		}
		var arg2 *time.Duration
		if args[2] != nil {
			arg2 = args[2].(*time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *RedisQueueForTest_PushRight_Call) Return(v uint64, err error) *RedisQueueForTest_PushRight_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *RedisQueueForTest_PushRight_Call) RunAndReturn(run func(ctx context.Context, message redis.QueueMessageEnvelope, ttl *time.Duration) (uint64, error)) *RedisQueueForTest_PushRight_Call {
	_c.Call.Return(run)
	return _c
}

// QueueName provides a mock function for the type RedisQueueForTest
func (_mock *RedisQueueForTest) QueueName() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for QueueName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// RedisQueueForTest_QueueName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueueName'
type RedisQueueForTest_QueueName_Call struct {
	*mock.Call
}

// QueueName is a helper method to define mock.On call
func (_e *RedisQueueForTest_Expecter) QueueName() *RedisQueueForTest_QueueName_Call {
	return &RedisQueueForTest_QueueName_Call{Call: _e.mock.On("QueueName")}
}

func (_c *RedisQueueForTest_QueueName_Call) Run(run func()) *RedisQueueForTest_QueueName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *RedisQueueForTest_QueueName_Call) Return(s string) *RedisQueueForTest_QueueName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *RedisQueueForTest_QueueName_Call) RunAndReturn(run func() string) *RedisQueueForTest_QueueName_Call {
	_c.Call.Return(run)
	return _c
}

// Remove provides a mock function for the type RedisQueueForTest
func (_mock *RedisQueueForTest) Remove(ctx context.Context, message redis.QueueMessageEnvelope) error {
	ret := _mock.Called(ctx, message)

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, redis.QueueMessageEnvelope) error); ok {
		r0 = returnFunc(ctx, message)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// RedisQueueForTest_Remove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remove'
type RedisQueueForTest_Remove_Call struct {
	*mock.Call
}

// Remove is a helper method to define mock.On call
//   - ctx context.Context
//   - message redis.QueueMessageEnvelope
func (_e *RedisQueueForTest_Expecter) Remove(ctx interface{}, message interface{}) *RedisQueueForTest_Remove_Call {
	return &RedisQueueForTest_Remove_Call{Call: _e.mock.On("Remove", ctx, message)}
}

func (_c *RedisQueueForTest_Remove_Call) Run(run func(ctx context.Context, message redis.QueueMessageEnvelope)) *RedisQueueForTest_Remove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 redis.QueueMessageEnvelope
		if args[1] != nil {
			arg1 = args[1].(redis.QueueMessageEnvelope)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *RedisQueueForTest_Remove_Call) Return(err error) *RedisQueueForTest_Remove_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *RedisQueueForTest_Remove_Call) RunAndReturn(run func(ctx context.Context, message redis.QueueMessageEnvelope) error) *RedisQueueForTest_Remove_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveAndMove provides a mock function for the type RedisQueueForTest
func (_mock *RedisQueueForTest) RemoveAndMove(ctx context.Context, destination string, message redis.QueueMessageEnvelope, insertOnLeft bool) error {
	ret := _mock.Called(ctx, destination, message, insertOnLeft)

	if len(ret) == 0 {
		panic("no return value specified for RemoveAndMove")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, redis.QueueMessageEnvelope, bool) error); ok {
		r0 = returnFunc(ctx, destination, message, insertOnLeft)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// RedisQueueForTest_RemoveAndMove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveAndMove'
type RedisQueueForTest_RemoveAndMove_Call struct {
	*mock.Call
}

// RemoveAndMove is a helper method to define mock.On call
//   - ctx context.Context
//   - destination string
//   - message redis.QueueMessageEnvelope
//   - insertOnLeft bool
func (_e *RedisQueueForTest_Expecter) RemoveAndMove(ctx interface{}, destination interface{}, message interface{}, insertOnLeft interface{}) *RedisQueueForTest_RemoveAndMove_Call {
	return &RedisQueueForTest_RemoveAndMove_Call{Call: _e.mock.On("RemoveAndMove", ctx, destination, message, insertOnLeft)}
}

func (_c *RedisQueueForTest_RemoveAndMove_Call) Run(run func(ctx context.Context, destination string, message redis.QueueMessageEnvelope, insertOnLeft bool)) *RedisQueueForTest_RemoveAndMove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 redis.QueueMessageEnvelope
		if args[2] != nil {
			arg2 = args[2].(redis.QueueMessageEnvelope)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *RedisQueueForTest_RemoveAndMove_Call) Return(err error) *RedisQueueForTest_RemoveAndMove_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *RedisQueueForTest_RemoveAndMove_Call) RunAndReturn(run func(ctx context.Context, destination string, message redis.QueueMessageEnvelope, insertOnLeft bool) error) *RedisQueueForTest_RemoveAndMove_Call {
	_c.Call.Return(run)
	return _c
}
