// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocktest

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewUnitTestCallbackCollector creates a new instance of UnitTestCallbackCollector. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUnitTestCallbackCollector(t interface {
	mock.TestingT
	Cleanup(func())
}) *UnitTestCallbackCollector {
	mock := &UnitTestCallbackCollector{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// UnitTestCallbackCollector is an autogenerated mock type for the UnitTestCallbackCollector type
type UnitTestCallbackCollector struct {
	mock.Mock
}

type UnitTestCallbackCollector_Expecter struct {
	mock *mock.Mock
}

func (_m *UnitTestCallbackCollector) EXPECT() *UnitTestCallbackCollector_Expecter {
	return &UnitTestCallbackCollector_Expecter{mock: &_m.Mock}
}

// OnComplete provides a mock function for the type UnitTestCallbackCollector
func (_mock *UnitTestCallbackCollector) OnComplete(ctx context.Context, instanceID string, err error, timestamp time.Time) {
	_mock.Called(ctx, instanceID, err, timestamp)
	return
}

// UnitTestCallbackCollector_OnComplete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnComplete'
type UnitTestCallbackCollector_OnComplete_Call struct {
	*mock.Call
}

// OnComplete is a helper method to define mock.On call
//   - ctx context.Context
//   - instanceID string
//   - err error
//   - timestamp time.Time
func (_e *UnitTestCallbackCollector_Expecter) OnComplete(ctx interface{}, instanceID interface{}, err interface{}, timestamp interface{}) *UnitTestCallbackCollector_OnComplete_Call {
	return &UnitTestCallbackCollector_OnComplete_Call{Call: _e.mock.On("OnComplete", ctx, instanceID, err, timestamp)}
}

func (_c *UnitTestCallbackCollector_OnComplete_Call) Run(run func(ctx context.Context, instanceID string, err error, timestamp time.Time)) *UnitTestCallbackCollector_OnComplete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 error
		if args[2] != nil {
			arg2 = args[2].(error)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *UnitTestCallbackCollector_OnComplete_Call) Return() *UnitTestCallbackCollector_OnComplete_Call {
	_c.Call.Return()
	return _c
}

func (_c *UnitTestCallbackCollector_OnComplete_Call) RunAndReturn(run func(ctx context.Context, instanceID string, err error, timestamp time.Time)) *UnitTestCallbackCollector_OnComplete_Call {
	_c.Run(run)
	return _c
}
