// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocknotify

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewConsumer creates a new instance of Consumer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewConsumer(t interface {
	mock.TestingT
	Cleanup(func())
}) *Consumer {
	mock := &Consumer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Consumer is an autogenerated mock type for the Consumer type
type Consumer struct {
	mock.Mock
}

type Consumer_Expecter struct {
	mock *mock.Mock
}

func (_m *Consumer) EXPECT() *Consumer_Expecter {
	return &Consumer_Expecter{mock: &_m.Mock}
}

// Start provides a mock function for the type Consumer
func (_mock *Consumer) Start(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Consumer_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type Consumer_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Consumer_Expecter) Start(ctx interface{}) *Consumer_Start_Call {
	return &Consumer_Start_Call{Call: _e.mock.On("Start", ctx)}
}

func (_c *Consumer_Start_Call) Run(run func(ctx context.Context)) *Consumer_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Consumer_Start_Call) Return(err error) *Consumer_Start_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Consumer_Start_Call) RunAndReturn(run func(ctx context.Context) error) *Consumer_Start_Call {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function for the type Consumer
func (_mock *Consumer) Stop(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Stop")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Consumer_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type Consumer_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Consumer_Expecter) Stop(ctx interface{}) *Consumer_Stop_Call {
	return &Consumer_Stop_Call{Call: _e.mock.On("Stop", ctx)}
}

func (_c *Consumer_Stop_Call) Run(run func(ctx context.Context)) *Consumer_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Consumer_Stop_Call) Return(err error) *Consumer_Stop_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Consumer_Stop_Call) RunAndReturn(run func(ctx context.Context) error) *Consumer_Stop_Call {
	_c.Call.Return(run)
	return _c
}
