// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocknotify

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewProducer creates a new instance of Producer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProducer(t interface {
	mock.TestingT
	Cleanup(func())
}) *Producer {
	mock := &Producer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Producer is an autogenerated mock type for the Producer type
type Producer struct {
	mock.Mock
}

type Producer_Expecter struct {
	mock *mock.Mock
}

func (_m *Producer) EXPECT() *Producer_Expecter {
	return &Producer_Expecter{mock: &_m.Mock}
}

// Start provides a mock function for the type Producer
func (_mock *Producer) Start(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Producer_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type Producer_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Producer_Expecter) Start(ctx interface{}) *Producer_Start_Call {
	return &Producer_Start_Call{Call: _e.mock.On("Start", ctx)}
}

func (_c *Producer_Start_Call) Run(run func(ctx context.Context)) *Producer_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Producer_Start_Call) Return(err error) *Producer_Start_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Producer_Start_Call) RunAndReturn(run func(ctx context.Context) error) *Producer_Start_Call {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function for the type Producer
func (_mock *Producer) Stop(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Stop")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Producer_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type Producer_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Producer_Expecter) Stop(ctx interface{}) *Producer_Stop_Call {
	return &Producer_Stop_Call{Call: _e.mock.On("Stop", ctx)}
}

func (_c *Producer_Stop_Call) Run(run func(ctx context.Context)) *Producer_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Producer_Stop_Call) Return(err error) *Producer_Stop_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Producer_Stop_Call) RunAndReturn(run func(ctx context.Context) error) *Producer_Stop_Call {
	_c.Call.Return(run)
	return _c
}
