// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockcommon

import (
	"context"

	"github.com/alwitt/goutils/redis"
	mock "github.com/stretchr/testify/mock"
)

// NewIPCMessageSend creates a new instance of IPCMessageSend. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIPCMessageSend(t interface {
	mock.TestingT
	Cleanup(func())
}) *IPCMessageSend {
	mock := &IPCMessageSend{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// IPCMessageSend is an autogenerated mock type for the IPCMessageSend type
type IPCMessageSend struct {
	mock.Mock
}

type IPCMessageSend_Expecter struct {
	mock *mock.Mock
}

func (_m *IPCMessageSend) EXPECT() *IPCMessageSend_Expecter {
	return &IPCMessageSend_Expecter{mock: &_m.Mock}
}

// EnqueueMessage provides a mock function for the type IPCMessageSend
func (_mock *IPCMessageSend) EnqueueMessage(ctx context.Context, msg redis.QueueMessageEnvelope) error {
	ret := _mock.Called(ctx, msg)

	if len(ret) == 0 {
		panic("no return value specified for EnqueueMessage")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, redis.QueueMessageEnvelope) error); ok {
		r0 = returnFunc(ctx, msg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// IPCMessageSend_EnqueueMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnqueueMessage'
type IPCMessageSend_EnqueueMessage_Call struct {
	*mock.Call
}

// EnqueueMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - msg redis.QueueMessageEnvelope
func (_e *IPCMessageSend_Expecter) EnqueueMessage(ctx interface{}, msg interface{}) *IPCMessageSend_EnqueueMessage_Call {
	return &IPCMessageSend_EnqueueMessage_Call{Call: _e.mock.On("EnqueueMessage", ctx, msg)}
}

func (_c *IPCMessageSend_EnqueueMessage_Call) Run(run func(ctx context.Context, msg redis.QueueMessageEnvelope)) *IPCMessageSend_EnqueueMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 redis.QueueMessageEnvelope
		if args[1] != nil {
			arg1 = args[1].(redis.QueueMessageEnvelope)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *IPCMessageSend_EnqueueMessage_Call) Return(err error) *IPCMessageSend_EnqueueMessage_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *IPCMessageSend_EnqueueMessage_Call) RunAndReturn(run func(ctx context.Context, msg redis.QueueMessageEnvelope) error) *IPCMessageSend_EnqueueMessage_Call {
	_c.Call.Return(run)
	return _c
}
