// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockcommon

import (
	"context"
	"time"

	"github.com/alwitt/goutils/redis"
	mock "github.com/stretchr/testify/mock"
)

// NewIPCMessageReceive creates a new instance of IPCMessageReceive. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIPCMessageReceive(t interface {
	mock.TestingT
	Cleanup(func())
}) *IPCMessageReceive {
	mock := &IPCMessageReceive{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// IPCMessageReceive is an autogenerated mock type for the IPCMessageReceive type
type IPCMessageReceive struct {
	mock.Mock
}

type IPCMessageReceive_Expecter struct {
	mock *mock.Mock
}

func (_m *IPCMessageReceive) EXPECT() *IPCMessageReceive_Expecter {
	return &IPCMessageReceive_Expecter{mock: &_m.Mock}
}

// DeleteBufferedMessage provides a mock function for the type IPCMessageReceive
func (_mock *IPCMessageReceive) DeleteBufferedMessage(ctx context.Context, msg redis.QueueMessageEnvelope) error {
	ret := _mock.Called(ctx, msg)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBufferedMessage")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, redis.QueueMessageEnvelope) error); ok {
		r0 = returnFunc(ctx, msg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// IPCMessageReceive_DeleteBufferedMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteBufferedMessage'
type IPCMessageReceive_DeleteBufferedMessage_Call struct {
	*mock.Call
}

// DeleteBufferedMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - msg redis.QueueMessageEnvelope
func (_e *IPCMessageReceive_Expecter) DeleteBufferedMessage(ctx interface{}, msg interface{}) *IPCMessageReceive_DeleteBufferedMessage_Call {
	return &IPCMessageReceive_DeleteBufferedMessage_Call{Call: _e.mock.On("DeleteBufferedMessage", ctx, msg)}
}

func (_c *IPCMessageReceive_DeleteBufferedMessage_Call) Run(run func(ctx context.Context, msg redis.QueueMessageEnvelope)) *IPCMessageReceive_DeleteBufferedMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 redis.QueueMessageEnvelope
		if args[1] != nil {
			arg1 = args[1].(redis.QueueMessageEnvelope)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *IPCMessageReceive_DeleteBufferedMessage_Call) Return(err error) *IPCMessageReceive_DeleteBufferedMessage_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *IPCMessageReceive_DeleteBufferedMessage_Call) RunAndReturn(run func(ctx context.Context, msg redis.QueueMessageEnvelope) error) *IPCMessageReceive_DeleteBufferedMessage_Call {
	_c.Call.Return(run)
	return _c
}

// DequeueBufferedMessage provides a mock function for the type IPCMessageReceive
func (_mock *IPCMessageReceive) DequeueBufferedMessage(ctx context.Context, blocking bool, maxWait *time.Duration) (redis.QueueMessageEnvelope, error) {
	ret := _mock.Called(ctx, blocking, maxWait)

	if len(ret) == 0 {
		panic("no return value specified for DequeueBufferedMessage")
	}

	var r0 redis.QueueMessageEnvelope
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, bool, *time.Duration) (redis.QueueMessageEnvelope, error)); ok {
		return returnFunc(ctx, blocking, maxWait)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, bool, *time.Duration) redis.QueueMessageEnvelope); ok {
		r0 = returnFunc(ctx, blocking, maxWait)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(redis.QueueMessageEnvelope)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, bool, *time.Duration) error); ok {
		r1 = returnFunc(ctx, blocking, maxWait)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// IPCMessageReceive_DequeueBufferedMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DequeueBufferedMessage'
type IPCMessageReceive_DequeueBufferedMessage_Call struct {
	*mock.Call
}

// DequeueBufferedMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - blocking bool
//   - maxWait *time.Duration
func (_e *IPCMessageReceive_Expecter) DequeueBufferedMessage(ctx interface{}, blocking interface{}, maxWait interface{}) *IPCMessageReceive_DequeueBufferedMessage_Call {
	return &IPCMessageReceive_DequeueBufferedMessage_Call{Call: _e.mock.On("DequeueBufferedMessage", ctx, blocking, maxWait)}
}

func (_c *IPCMessageReceive_DequeueBufferedMessage_Call) Run(run func(ctx context.Context, blocking bool, maxWait *time.Duration)) *IPCMessageReceive_DequeueBufferedMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 bool
		if args[1] != nil {
			arg1 = args[1].(bool)
		}
		var arg2 *time.Duration
		if args[2] != nil {
			arg2 = args[2].(*time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *IPCMessageReceive_DequeueBufferedMessage_Call) Return(queueMessageEnvelope redis.QueueMessageEnvelope, err error) *IPCMessageReceive_DequeueBufferedMessage_Call {
	_c.Call.Return(queueMessageEnvelope, err)
	return _c
}

func (_c *IPCMessageReceive_DequeueBufferedMessage_Call) RunAndReturn(run func(ctx context.Context, blocking bool, maxWait *time.Duration) (redis.QueueMessageEnvelope, error)) *IPCMessageReceive_DequeueBufferedMessage_Call {
	_c.Call.Return(run)
	return _c
}

// DequeueMessage provides a mock function for the type IPCMessageReceive
func (_mock *IPCMessageReceive) DequeueMessage(ctx context.Context, blocking bool, maxWait *time.Duration) (redis.QueueMessageEnvelope, error) {
	ret := _mock.Called(ctx, blocking, maxWait)

	if len(ret) == 0 {
		panic("no return value specified for DequeueMessage")
	}

	var r0 redis.QueueMessageEnvelope
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, bool, *time.Duration) (redis.QueueMessageEnvelope, error)); ok {
		return returnFunc(ctx, blocking, maxWait)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, bool, *time.Duration) redis.QueueMessageEnvelope); ok {
		r0 = returnFunc(ctx, blocking, maxWait)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(redis.QueueMessageEnvelope)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, bool, *time.Duration) error); ok {
		r1 = returnFunc(ctx, blocking, maxWait)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// IPCMessageReceive_DequeueMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DequeueMessage'
type IPCMessageReceive_DequeueMessage_Call struct {
	*mock.Call
}

// DequeueMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - blocking bool
//   - maxWait *time.Duration
func (_e *IPCMessageReceive_Expecter) DequeueMessage(ctx interface{}, blocking interface{}, maxWait interface{}) *IPCMessageReceive_DequeueMessage_Call {
	return &IPCMessageReceive_DequeueMessage_Call{Call: _e.mock.On("DequeueMessage", ctx, blocking, maxWait)}
}

func (_c *IPCMessageReceive_DequeueMessage_Call) Run(run func(ctx context.Context, blocking bool, maxWait *time.Duration)) *IPCMessageReceive_DequeueMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 bool
		if args[1] != nil {
			arg1 = args[1].(bool)
		}
		var arg2 *time.Duration
		if args[2] != nil {
			arg2 = args[2].(*time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *IPCMessageReceive_DequeueMessage_Call) Return(queueMessageEnvelope redis.QueueMessageEnvelope, err error) *IPCMessageReceive_DequeueMessage_Call {
	_c.Call.Return(queueMessageEnvelope, err)
	return _c
}

func (_c *IPCMessageReceive_DequeueMessage_Call) RunAndReturn(run func(ctx context.Context, blocking bool, maxWait *time.Duration) (redis.QueueMessageEnvelope, error)) *IPCMessageReceive_DequeueMessage_Call {
	_c.Call.Return(run)
	return _c
}

// ReEnqueueOnMainQueue provides a mock function for the type IPCMessageReceive
func (_mock *IPCMessageReceive) ReEnqueueOnMainQueue(ctx context.Context, msg redis.QueueMessageEnvelope) error {
	ret := _mock.Called(ctx, msg)

	if len(ret) == 0 {
		panic("no return value specified for ReEnqueueOnMainQueue")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, redis.QueueMessageEnvelope) error); ok {
		r0 = returnFunc(ctx, msg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// IPCMessageReceive_ReEnqueueOnMainQueue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReEnqueueOnMainQueue'
type IPCMessageReceive_ReEnqueueOnMainQueue_Call struct {
	*mock.Call
}

// ReEnqueueOnMainQueue is a helper method to define mock.On call
//   - ctx context.Context
//   - msg redis.QueueMessageEnvelope
func (_e *IPCMessageReceive_Expecter) ReEnqueueOnMainQueue(ctx interface{}, msg interface{}) *IPCMessageReceive_ReEnqueueOnMainQueue_Call {
	return &IPCMessageReceive_ReEnqueueOnMainQueue_Call{Call: _e.mock.On("ReEnqueueOnMainQueue", ctx, msg)}
}

func (_c *IPCMessageReceive_ReEnqueueOnMainQueue_Call) Run(run func(ctx context.Context, msg redis.QueueMessageEnvelope)) *IPCMessageReceive_ReEnqueueOnMainQueue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 redis.QueueMessageEnvelope
		if args[1] != nil {
			arg1 = args[1].(redis.QueueMessageEnvelope)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *IPCMessageReceive_ReEnqueueOnMainQueue_Call) Return(err error) *IPCMessageReceive_ReEnqueueOnMainQueue_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *IPCMessageReceive_ReEnqueueOnMainQueue_Call) RunAndReturn(run func(ctx context.Context, msg redis.QueueMessageEnvelope) error) *IPCMessageReceive_ReEnqueueOnMainQueue_Call {
	_c.Call.Return(run)
	return _c
}
